### PR TITLE
(#431) FileCacheV2 + Concurrent chunked file downloading

### LINKED ISSUE #431: [BUG] When quickly swiping through images in the gallery previous downloading files do not get canceled
STR:
- Open any thread on /hr/.
- Start swiping through the images without waiting for them to be completely downloaded.
- After 10-20 swipes the next one will get stuck and won't be downloaded (then you will probably see a chain of "Failed to load image" toasts).

We should doublecheck the canceling mechanism.

 It apparently got even worse with the addition of the `Thread.sleep()` after a every failed attempt to download an image. These `Thread.sleeps` should be removed completely. 

This is also probably the same issue as the one where webm won't load after quickly swiping through lots of them.

### PR DESCRIPTION
**Pull request by K1rakishou**
Closes #431, #150, #466, #420, #56 and maybe some other issues I couldn't find. Also reverts back webm streaming.
**Ready to be merged.**

FileCache was completely rewritten (as well as CacheHandler), FileCacheDownloader was merged into FileCache. FileCache now uses RxJava for concurrency and in the future it will be completely reactive (when MultiImageView is rewritten as well). 
Some additional things that were also changed in this PR:

- FileCache now executes asynchronous requests (instead of synchronous) which can be canceled while they are in-flight (which was impossible in the previous implementation because they were blocking, the only way to do it was via Thread.currentThread().interrupt() but it was still pretty tricky to do).
- FileCache now uses two queues with their own threadpools: one to download images when swiping in the gallery and the other one when downloading whole albums. So now you can download albums AND swipe images in the album at the same time. If a file is already being downloaded via gallery downloading and you swipe to it in the gallery, this file WON'T be downloaded twice. Instead you will subscribe to an already active request and once it completes that image image will be returned.
- Cache size was increased to 512MB. Prefetch cache remains the same but probably it may be increased as well. The reasoning to increase the cache size is that 100MB is not enough for some boards (the cache trimming is called pretty often (and it is now slower than it was before), you just need to swipe through 20 5MB webms on /wsg/ to fill up the cache) and there are other chans where the file limit is up to 25MB (!!!). But maybe 512MB is way too high. Maybe it should be like 350MB or something.
- CacheHandler now DOES NOT use LastModified flag to tell apart fresh cache files from the old because LastModified DOES NOT WORK on some android versions as well as some phones (it doesn't even work on the emulator for me). Instead it uses a second file (meta file) for every cache file where two parameters are stored: creation time and a "isDownloaded" flag.
- Album image preloading now works when swiping in both directions (in the previous implementation it was only preloading when swiping "forward", now it also preloads "next" file when swiping "backwards"). 
- We don't cancel previous download ("current - 1"/"current + 1") when swiping forward/backward, instead we cancel a file at "current position - 2" (or + 2 in case of backward swipes) because it would sometimes cancel an image right when the user swipes back right after swiping forward. Should be better now.
- There are now three different OkHttpClient instances: One for posting (the one which supports proxies), one for image downloading and one for local threads downloading. All of them use their own thread pools. Also, we now don't use proxied OkHttpClient for image downloading, only for posting. Two of them are injected via "Named" annotation the third one (proxied) is not for now bu should be in the future. By doing so we will be able to remove the ProxiedHttpClient wrapper.

**UPDATE:**
This PR will also have a new experimental method for files/images downloading. Instead of downloading a file sequentially, there will be a new setting that will allow you to download a file in separate chunks **concurrently**. In theory this should drastically improve image/file download speed. Basically it will work like the old boomer software called **Download Master**. The setting will allow you to change the amount of chunks every file will be split into. Let's say you change it to 4. That means, that if you try to download a file that has a size of 4MB it will be split into 4 chunks 1MB each and they will be downloaded concurrently which in theory should boost the download time **4x times**. So if it usually downloads in 4 seconds it should be downloaded in **1 second**.  

I haven't tested it yet so it's only theoretical because 4chan may limit concurrent connections to the same resource and if that's true then there is nothing I can do. But I will still leave this so that people can use it with other chans.

~~This PR also fixes a bug when downloading sometimes would get completely stuck and OkHttp won't accept any new requests immediatelly throwing SocketTimeoutException. This is a OkHttp bug - https://github.com/square/okhttp/issues/3146 and to fix it I had to disable ConnectionPooling which is pretty bad since it will create a new thread for every new request. **We should revert it back once it is fixed in OkHttp 4.3 which should be released soon!**~~

**UPDATE2:**
Also, webm streaming is also reverted back in this PR. But it does not work good with 4chan because 4chan does not allow concurrent access to the same file/image. But it works when a file is cached by cloudflare and it works on other chans with good servers so I'll leave it.

**UPDATE3:**
Pretty much done. So this thing works really bad with 4chan images/webms/gifs that ARE NOT CACHED by the cloudflare. 4chan blocks any concurrent access to the same resource and limits download speed by A LOT (like it may take up to 15 fucking seconds for a 3MB picture while it takes like 50ms for the same picture once it gets cached by the cloudflare). The same goes to webm streaming. But it works pretty good with images that are cached by the cloudflare and on some other chans with good servers (like 2ch.hk). So I will leave both of these settings available.
The good news are for those people who live closely to the place where 4chan servers are located: they should have a really good download speed with this thing (well it should have already been great), as well as people living close to the cloudflare CDN servers (EU/US). Once anybody loads an image, and it gets cached by the cloudflare, it will be then served from the cache for anyone who lives nearby.

Now what's left are unit tests. I'm planning to write tons of unit tests to cover all this shit so we don't break it accidentally. Gonna take a little bit more of time.

**UPDATE4:**
Wew this thing got out of hands and now it's 6.6K LOCs. 
Ok, it's done. I did a little bit of testing and here are the things I've checked manually:

```
- Gallery image viewing with regular and chunked downloads.....OK
- Test media prefetching.......................................OK
- Test that media prefetching canceling works..................OK
- Test gallery batch downloading...............................OK
- Test local threads downloading...............................OK
- Test and make sure that the OkHttp bug is gone...............OK
- Test and make sure that clipboard image link downloading.....OK
- Test apk update download.....................................OK
```

I might forgot something.
~~Debug apk:  [Kuroba-3c18460.zip](https://github.com/Adamantcheese/Kuroba/files/4020217/Kuroba-3c18460.zip)~~

**UPDATE5:**
Now for vichan and futaba we also parse and use the md5 parameter for every file. I use it to check, after a file has been downloaded, that the file is not corrupted. We can also use it now to implement post filtering based on file hash.

~~New Debug apk: [Kuroba-c3e0956.zip](https://github.com/Adamantcheese/Kuroba/files/4022024/Kuroba-c3e0956.zip)~~

**UPDATE6:**
~~New Debug apk: [Kuroba-5e3cc95.zip](https://github.com/Adamantcheese/Kuroba/files/4023260/Kuroba-5e3cc95.zip)~~

**UPDATE7:**
Now the app shouldn't hang, when downloading batches of images, until all images are downloaded.

New Debug apk: 
[Kuroba-c7dd250.zip](https://github.com/Adamantcheese/Kuroba/files/4049391/Kuroba-c7dd250.zip)

**UPDATE8:**
Alright, after a couple of weeks of using it, I haven't had any problems and I think it's good to go. One thing I should change though. It's the setting where you select the amount of chunks that will be downloaded concurrently. I think 6 and 8 chunks is overkill. It should be 1, 2 and 4. 6 and 8 do not really speed up the download speed and they may even lag the device. So yeah, 1, 2 and 4 should be enough.

### CODE REVIEW

**Comment by K1rakishou** [comment]
~~Oh, I forgot to change the prefetcher to also use the batched image downloading queue, so you can view images while prefetcher downloads everything in a thread.~~

**Comment by K1rakishou** [comment]
~~Should also add a setting to force the downloader OkHttpClient to only use HTTP 1.1 protocol. Right now it's the default so it uses HTTP 1.1 and 2.0 and the latter may be the cause of all the problems.~~
No, HTTP 2.0 has nothing to do with that problem.

File: Kuroba/app/src/main/java/com/github/adamantcheese/chan/core/cache/CacheHandler.kt [hunk 1]
```diff
@@ -0,0 +1,802 @@
...
+                                "Couldn't read content cache file meta, " +
+                                        "read = $read, expected = $length"
+                        )
+                    }
+
+                    val content = String(contentBuffer)
+                    val split = content.split(",").toTypedArray()
+                    if (split.size != 2) {
+                        throw IOException(
+                                "Couldn't split meta content, split.size = ${split.size}"
```
Comment (K1rakishou) [inline Kuroba/app/src/main/java/com/github/adamantcheese/chan/core/cache/CacheHandler.kt]: Add the content itself

File: Kuroba/app/src/main/java/com/github/adamantcheese/chan/core/cache/CacheHandler.kt [hunk 2]
```diff
@@ -0,0 +1,802 @@
...
+            Logger.e(TAG, "Couldn't read cache file meta")
+            return null
+        }
+
+        if (fileManager.getLength(file) <= 0) {
+            // File is empty
+            return null
+        }
+
+        require(fileManager.getName(file).endsWith(CACHE_META_EXTENSION)) {
```
Comment (K1rakishou) [inline Kuroba/app/src/main/java/com/github/adamantcheese/chan/core/cache/CacheHandler.kt]: Probably a better idea is to return null here

File: Kuroba/app/src/main/java/com/github/adamantcheese/chan/utils/ChanUtils.kt [hunk 3]
```diff
@@ -0,0 +1,15 @@
...
+
+import com.github.adamantcheese.chan.core.model.orm.Loadable
+
+object ChanUtils {
+
+    /**
+     * Extracts and converts to a string only the info that we are interested in from this loadable
+     */
+    @JvmStatic
+    fun loadableToString(loadable: Loadable): String {
```
Comment (Adamantcheese) [inline Kuroba/app/src/main/java/com/github/adamantcheese/chan/utils/ChanUtils.kt]: You've moved this from ThreadSaveManager, but it would be better if this function was internal to the Loadable object, say, `toShortString` or something of that sort.

Comment (K1rakishou) [reply Kuroba/app/src/main/java/com/github/adamantcheese/chan/utils/ChanUtils.kt]: Yeah, that's probably where it should be.

**Comment by K1rakishou** [comment]
~~We also should somehow avoid cancelation of images at positions -1, 0 and +1 (where 0 is the current image the user is viewing in the gallery) to avoid the opening canceled images.~~

File: Kuroba/app/src/main/java/com/github/adamantcheese/chan/core/cache/CacheHandler.kt [hunk 4]
```diff
@@ -0,0 +1,802 @@
...
+import java.io.PrintWriter
+import java.util.*
+import java.util.concurrent.Executors
+import java.util.concurrent.TimeUnit
+import java.util.concurrent.atomic.AtomicBoolean
+import java.util.concurrent.atomic.AtomicLong
+
+/**
+ * CacheHandler has been re-worked a little bit because old implementation was relying on the
+ * lastModified file flag which doesn't work on some Android versions/different phone. It was decided
```
Comment (K1rakishou) [inline Kuroba/app/src/main/java/com/github/adamantcheese/chan/core/cache/CacheHandler.kt]: phones

File: Kuroba/app/src/main/java/com/github/adamantcheese/chan/core/cache/CacheHandler.kt [hunk 5]
```diff
@@ -0,0 +1,802 @@
...
+ * 2. A flag that indicates whether the download has been completed or not.
+ *
+ *
+ * We need creation time to not delete cache file for active downloads or for downloads that has
+ * just been completed (otherwise the user may see a black screen instead of an image/webm). The
+ * minimum cache file life time is 5 minutes. That means we won't delete any cache file (and their
+ * meta files) for at least 5 minutes.
+ *
+ * The cache size has been increased from 100MB up to 512MB. The reasoning for that is that there
+ * are some boards on 4chan where a single file make take up to 5MB. Also, there are other chans
```
Comment (K1rakishou) [inline Kuroba/app/src/main/java/com/github/adamantcheese/chan/core/cache/CacheHandler.kt]: may take

File: Kuroba/app/src/main/java/com/github/adamantcheese/chan/core/cache/CacheHandler.kt [hunk 6]
```diff
@@ -0,0 +1,802 @@
...
+    }
+
+    /**
+     * Marks the file as a downloaded (sets a flag in it's meta info). If meta info cannot be read
+     * deletes the file so it can be re-downloaded again.
+     * */
+    fun markFileDownloaded(output: RawFile): Boolean {
+        return try {
+            if (!fileManager.exists(output)) {
+                Logger.e(TAG, "File does not exist! file = ${output.getFullPath()}")
```
Comment (K1rakishou) [inline Kuroba/app/src/main/java/com/github/adamantcheese/chan/core/cache/CacheHandler.kt:242]: Should probably also add deleteCacheFile() here to delete the cache file meta in case it still exists.

File: Kuroba/app/src/main/java/com/github/adamantcheese/chan/core/cache/FileCacheV2.kt [hunk 7]
```diff
@@ -0,0 +1,1077 @@
...
+
+    /**
+     * We use two rx queues here. One for the normal file/image downloading (like when user clicks a
+     * image thumbnail to view a full-size image) and the other queue for when user downloads full
+     * image albums or for media-prefetching etc.
+     * */
+    private val normalRequestQueue = PublishProcessor.create<String>()
+    private val batchRequestQueue = PublishProcessor.create<List<String>>()
+
+    private val threadsCount = (Runtime.getRuntime().availableProcessors() / 2).coerceAtLeast(4)
```
Comment (K1rakishou) [inline Kuroba/app/src/main/java/com/github/adamantcheese/chan/core/cache/FileCacheV2.kt:62]: This should probably be set to 3 instead of 4.

**Comment by K1rakishou** [comment]
Still not ready.

**Comment by K1rakishou** [comment]
```
     Caused by: java.util.ConcurrentModificationException
        at java.util.ArrayList$Itr.next(ArrayList.java:860)
        at com.github.adamantcheese.chan.core.cache.downloader.CancelableDownload$dispose$1.run(CancelableDownload.kt:118)
        at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:462)
        at java.util.concurrent.FutureTask.run(FutureTask.java:266)
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1167)
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:641)
        at java.lang.Thread.run(Thread.java:919)
```

~~This probably happens because `disposeFuncList` is using different locks when adding a new callback and when clearing all the callbacks in dispose() method.~~

**Comment by K1rakishou** [comment]
~~TODO: when opening an image it also preloads PREVIOUS image. I think we shouldn't preload anything here because we don't know which direction the user will swipe next (and the user may not do that at all, just close the image) so it's kinda wasteful. We should only preload prev/next images when the user swipes forward/backward.~~

File: Kuroba/app/src/main/java/com/github/adamantcheese/chan/core/cache/downloader/ConcurrentChunkedFileDownloader.kt [hunk 8]
```diff
@@ -0,0 +1,558 @@
...
+                                "nor ChunkDownloadEvent.ChunkSuccess!!!"
+                    }
+                }
+                .publish()
+                // This is fucking important! Do not change this value unless you
+                // want to change the amount of separate streams!!! Right now we need
+                // only two.
+                .autoConnect(2)
+
+        // First separate stream.
```
Comment (K1rakishou) [inline Kuroba/app/src/main/java/com/github/adamantcheese/chan/core/cache/downloader/ConcurrentChunkedFileDownloader.kt:176]: Update comment.

File: Kuroba/app/src/main/java/com/github/adamantcheese/chan/core/cache/downloader/ConcurrentChunkedFileDownloader.kt [hunk 9]
```diff
@@ -0,0 +1,558 @@
...
+                            url,
+                            downloadedChunks as List<ChunkDownloadEvent.ChunkSuccess>,
+                            output,
+                            startTime
+                    )
+                }
+
+        // So why are we splitting a reactive stream in two? Because we need to do some
+        // additional handling of ChunkedSuccess events but we don't want to do that
+        // for Exception and ChunkedProgress events (We want to pass them downstream
```
Comment (K1rakishou) [inline Kuroba/app/src/main/java/com/github/adamantcheese/chan/core/cache/downloader/ConcurrentChunkedFileDownloader.kt]: Update comment.

File: Kuroba/app/src/main/java/com/github/adamantcheese/chan/core/cache/downloader/ActiveDownloads.kt [hunk 10]
```diff
@@ -0,0 +1,72 @@
...
+    }
+
+    fun updateDownloaded(url: String, downloaded: Long) {
+        synchronized(activeDownloads) {
+            activeDownloads[url]?.downloaded?.set(downloaded)
+        }
+    }
+
+    fun addDisposeFunc(url: String, disposeFunc: () -> Unit) {
+        synchronized(activeDownloads) {
```
Comment (K1rakishou) [inline Kuroba/app/src/main/java/com/github/adamantcheese/chan/core/cache/downloader/ActiveDownloads.kt]: Add a check to not add any new dispose function (and dispose of them immediately) if the state of the CancelableDownload is canceled (and stopped?)

File: Kuroba/app/src/main/java/com/github/adamantcheese/chan/core/cache/downloader/PartialContentSupportChecker.kt [hunk 11]
```diff
@@ -0,0 +1,148 @@
...
+                        emitter.onError(e)
+                    } else {
+                        emitter.onError(
+                                FileCacheException.CancellationException(DownloadState.Canceled, url)
+                        )
+                    }
+                }
+
+                override fun onResponse(call: Call, response: Response) {
+                    val statusCode = response.code
```
Comment (K1rakishou) [inline Kuroba/app/src/main/java/com/github/adamantcheese/chan/core/cache/downloader/PartialContentSupportChecker.kt]: Extract into a separate function.

File: Kuroba/app/src/main/java/com/github/adamantcheese/chan/core/presenter/ImageViewerPresenter.java [hunk 12]
```diff
@@ -222,16 +244,21 @@ private void onPageSwipedTo(int position) {
...
+        }
 
         // Already in LOWRES mode
         if (callback.getImageMode(postImage) == LOWRES) {
             onLowResInCenter();
         }
-        // Else let onModeLoaded handle it
-
-        callback.showProgress(progress.get(selectedPosition) >= 0f);
-        callback.onLoadProgress(progress.get(selectedPosition));
```
Comment (K1rakishou) [inline Kuroba/app/src/main/java/com/github/adamantcheese/chan/core/presenter/ImageViewerPresenter.java:234]: I should actually probably use these two methods here but with default values so that we show progress bar immediatelly without having to wait the response from the server for the  HEAD request.

File: Kuroba/app/src/main/java/com/github/adamantcheese/chan/ui/view/MultiImageView.java [hunk 13]
```diff
@@ -335,13 +360,13 @@ public void onSuccess(RawFile file) {
             }
 
             @Override
-            public void onFail(boolean notFound) {
+            public void onFail(Exception exception) {
                 BackgroundUtils.ensureMainThread();
 
-                if (notFound) {
+                if (exception instanceof FileCacheException.FileNotFoundOnTheServerException) {
```
Comment (K1rakishou) [inline Kuroba/app/src/main/java/com/github/adamantcheese/chan/ui/view/MultiImageView.java]: I should use here another callback (onNotFound)

**Comment by K1rakishou** [comment]
```
Caused by: java.util.concurrent.ExecutionException: java.lang.IllegalStateException: Unbalanced enter/exit
        at java.util.concurrent.FutureTask.report(FutureTask.java:123)
        at java.util.concurrent.FutureTask.get(FutureTask.java:207)
        at com.github.adamantcheese.chan.core.cache.downloader.CancelableDownload.dispose(CancelableDownload.kt:115)
        at com.github.adamantcheese.chan.core.cache.downloader.CancelableDownload.cancel(CancelableDownload.kt:97)
        at com.github.adamantcheese.chan.core.cache.downloader.CancelableDownload.cancel(CancelableDownload.kt:64)
        at com.github.adamantcheese.chan.core.presenter.ImageViewerPresenter.onExit(ImageViewerPresenter.java:149)
        at com.github.adamantcheese.chan.core.presenter.ImageViewerPresenter.onTap(ImageViewerPresenter.java:415)
        at com.github.adamantcheese.chan.ui.view.MultiImageView.onClick(MultiImageView.java:259)
        at android.view.View.performClick(View.java:7140)
        at com.davemorrissey.labs.subscaleview.SubsamplingScaleImageView$2.onSingleTapConfirmed(SubsamplingScaleImageView.java:565)
        at android.view.GestureDetector$GestureHandler.handleMessage(GestureDetector.java:323)
        at android.os.Handler.dispatchMessage(Handler.java:107)
        at android.os.Looper.loop(Looper.java:214)
        at android.app.ActivityThread.main(ActivityThread.java:7356)
        at java.lang.reflect.Method.invoke(Native Method) 
        at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:492) 
        at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:930) 
     Caused by: java.lang.IllegalStateException: Unbalanced enter/exit
        at okio.AsyncTimeout.enter(AsyncTimeout.kt:49)
        at okio.AsyncTimeout$source$1.read(AsyncTimeout.kt:157)
        at okio.RealBufferedSource.read(RealBufferedSource.kt:41)
        at okhttp3.internal.http1.Http1ExchangeCodec$AbstractSource.read(Http1ExchangeCodec.kt:352)
        at okhttp3.internal.http1.Http1ExchangeCodec$FixedLengthSource.read(Http1ExchangeCodec.kt:389)
        at okhttp3.internal.Util.skipAll(Util.kt:337)
        at okhttp3.internal.Util.discard(Util.kt:358)
        at okhttp3.internal.http1.Http1ExchangeCodec$FixedLengthSource.close(Http1ExchangeCodec.kt:408)
        at okio.ForwardingSource.close(ForwardingSource.kt:34)
        at okhttp3.internal.connection.Exchange$ResponseBodySource.close(Exchange.kt:306)
        at okio.RealBufferedSource.close(RealBufferedSource.kt:461)
        at okhttp3.internal.Util.closeQuietly(Util.kt:480)
        at okhttp3.ResponseBody.close(ResponseBody.kt:192)
        at okhttp3.internal.Util.closeQuietly(Util.kt:480)
        at com.github.adamantcheese.chan.core.cache.downloader.ConcurrentChunkedFileDownloader$pipeChunk$1$disposeFunc$1.invoke(ConcurrentChunkedFileDownloader.kt:329)
        at com.github.adamantcheese.chan.core.cache.downloader.ConcurrentChunkedFileDownloader$pipeChunk$1$disposeFunc$1.invoke(ConcurrentChunkedFileDownloader.kt:25)
        at com.github.adamantcheese.chan.core.cache.downloader.CancelableDownload$dispose$1.run(CancelableDownload.kt:110)
        at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:462)
        at java.util.concurrent.FutureTask.run(FutureTask.java:266)
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1167)
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:641)
        at java.lang.Thread.run(Thread.java:919)
2019-12-27 17:45:32.810 E/Kuroba-dev | UNCAUGHT: java.lang.RuntimeException: java.lang.reflect.InvocationTargetException
        at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:502)
        at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:930)
     Caused by: java.lang.reflect.InvocationTargetException
        at java.lang.reflect.Method.invoke(Native Method)
        at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:492)
        at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:930) 
     Caused by: java.util.concurrent.ExecutionException: java.lang.IllegalStateException: Unbalanced enter/exit
        at java.util.concurrent.FutureTask.report(FutureTask.java:123)
        at java.util.concurrent.FutureTask.get(FutureTask.java:207)
        at com.github.adamantcheese.chan.core.cache.downloader.CancelableDownload.dispose(CancelableDownload.kt:115)
        at com.github.adamantcheese.chan.core.cache.downloader.CancelableDownload.cancel(CancelableDownload.kt:97)
        at com.github.adamantcheese.chan.core.cache.downloader.CancelableDownload.cancel(CancelableDownload.kt:64)
        at com.github.adamantcheese.chan.core.presenter.ImageViewerPresenter.onExit(ImageViewerPresenter.java:149)
        at com.github.adamantcheese.chan.core.presenter.ImageViewerPresenter.onTap(ImageViewerPresenter.java:415)
        at com.github.adamantcheese.chan.ui.view.MultiImageView.onClick(MultiImageView.java:259)
        at android.view.View.performClick(View.java:7140)
        at com.davemorrissey.labs.subscaleview.SubsamplingScaleImageView$2.onSingleTapConfirmed(SubsamplingScaleImageView.java:565)
        at android.view.GestureDetector$GestureHandler.handleMessage(GestureDetector.java:323)
        at android.os.Handler.dispatchMessage(Handler.java:107)
        at android.os.Looper.loop(Looper.java:214)
        at android.app.ActivityThread.main(ActivityThread.java:7356)
        at java.lang.reflect.Method.invoke(Native Method) 
        at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:492) 
        at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:930) 
     Caused by: java.lang.IllegalStateException: Unbalanced enter/exit
        at okio.AsyncTimeout.enter(AsyncTimeout.kt:49)
        at okio.AsyncTimeout$source$1.read(AsyncTimeout.kt:157)
        at okio.RealBufferedSource.read(RealBufferedSource.kt:41)
        at okhttp3.internal.http1.Http1ExchangeCodec$AbstractSource.read(Http1ExchangeCodec.kt:352)
        at okhttp3.internal.http1.Http1ExchangeCodec$FixedLengthSource.read(Http1ExchangeCodec.kt:389)
        at okhttp3.internal.Util.skipAll(Util.kt:337)
        at okhttp3.internal.Util.discard(Util.kt:358)
        at okhttp3.internal.http1.Http1ExchangeCodec$FixedLengthSource.close(Http1ExchangeCodec.kt:408)
        at okio.ForwardingSource.close(ForwardingSource.kt:34)
        at okhttp3.internal.connection.Exchange$ResponseBodySource.close(Exchange.kt:306)
        at okio.RealBufferedSource.close(RealBufferedSource.kt:461)
        at okhttp3.internal.Util.closeQuietly(Util.kt:480)
        at okhttp3.ResponseBody.close(ResponseBody.kt:192)
        at okhttp3.internal.Util.closeQuietly(Util.kt:480)
        at com.github.adamantcheese.chan.core.cache.downloader.ConcurrentChunkedFileDownloader$pipeChunk$1$disposeFunc$1.invoke(ConcurrentChunkedFileDownloader.kt:329)
        at com.github.adamantcheese.chan.core.cache.downloader.ConcurrentChunkedFileDownloader$pipeChunk$1$disposeFunc$1.invoke(ConcurrentChunkedFileDownloader.kt:25)
        at com.github.adamantcheese.chan.core.cache.downloader.CancelableDownload$dispose$1.run(CancelableDownload.kt:110)
        at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:462)
        at java.util.concurrent.FutureTask.run(FutureTask.java:266)
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1167)
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:641)
        at java.lang.Thread.run(Thread.java:919)
```

Fixed.

**Comment by K1rakishou** [comment]
```
2019-12-27 18:55:16.847 E/Kuroba-dev | FileCacheV2: [ConcurrentChunkedFileDownloaderThread-2]: Unknown exception, class = io.reactivex.exceptions.CompositeException, message = 2 exceptions occurred. 
2019-12-27 18:55:16.848 E/Kuroba-dev | APP: RxJava undeliverable exception
    io.reactivex.exceptions.CompositeException: 2 exceptions occurred. 
        at io.reactivex.internal.util.ExceptionHelper.addThrowable(ExceptionHelper.java:67)
        at io.reactivex.internal.util.AtomicThrowable.addThrowable(AtomicThrowable.java:34)
        at io.reactivex.internal.operators.flowable.FlowableFlatMap$MergeSubscriber.innerError(FlowableFlatMap.java:598)
        at io.reactivex.internal.operators.flowable.FlowableFlatMap$InnerSubscriber.onError(FlowableFlatMap.java:672)
        at io.reactivex.internal.operators.flowable.FlowableFlatMap$MergeSubscriber.checkTerminate(FlowableFlatMap.java:567)
        at io.reactivex.internal.operators.flowable.FlowableFlatMap$MergeSubscriber.drainLoop(FlowableFlatMap.java:374)
        at io.reactivex.internal.operators.flowable.FlowableFlatMap$MergeSubscriber.drain(FlowableFlatMap.java:366)
        at io.reactivex.internal.operators.flowable.FlowableFlatMap$MergeSubscriber.onError(FlowableFlatMap.java:325)
        at io.reactivex.internal.subscribers.BasicFuseableSubscriber.onError(BasicFuseableSubscriber.java:101)
        at io.reactivex.internal.operators.flowable.FlowableObserveOn$BaseObserveOnSubscriber.checkTerminated(FlowableObserveOn.java:209)
        at io.reactivex.internal.operators.flowable.FlowableObserveOn$ObserveOnSubscriber.runAsync(FlowableObserveOn.java:399)
        at io.reactivex.internal.operators.flowable.FlowableObserveOn$BaseObserveOnSubscriber.run(FlowableObserveOn.java:176)
        at io.reactivex.internal.schedulers.ExecutorScheduler$ExecutorWorker$BooleanRunnable.run(ExecutorScheduler.java:288)
        at io.reactivex.internal.schedulers.ExecutorScheduler$ExecutorWorker.run(ExecutorScheduler.java:253)
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1167)
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:641)
        at java.lang.Thread.run(Thread.java:919)
      ComposedException 1 :
    	com.github.adamantcheese.chan.core.cache.downloader.FileCacheException$CancellationException: CancellationException for request with url = https://i.4cdn.org/g/1577462011089.gif, state = Canceled
        at com.github.adamantcheese.chan.core.cache.downloader.ConcurrentChunkedFileDownloader.throwCancellationException(ConcurrentChunkedFileDownloader.kt:462)
        at com.github.adamantcheese.chan.core.cache.downloader.ConcurrentChunkedFileDownloader.access$throwCancellationException(ConcurrentChunkedFileDownloader.kt:25)
        at com.github.adamantcheese.chan.core.cache.downloader.ConcurrentChunkedFileDownloader$pipeChunk$1.subscribe(ConcurrentChunkedFileDownloader.kt:357)
        at io.reactivex.internal.operators.flowable.FlowableCreate.subscribeActual(FlowableCreate.java:71)
        at io.reactivex.Flowable.subscribe(Flowable.java:14918)
        at io.reactivex.Flowable.subscribe(Flowable.java:14865)
        at io.reactivex.internal.operators.flowable.FlowableRetryPredicate$RetrySubscriber.subscribeNext(FlowableRetryPredicate.java:124)
        at io.reactivex.internal.operators.flowable.FlowableRetryPredicate.subscribeActual(FlowableRetryPredicate.java:42)
        at io.reactivex.Flowable.subscribe(Flowable.java:14918)
        at io.reactivex.Flowable.subscribe(Flowable.java:14865)
        at io.reactivex.internal.operators.flowable.FlowableFlatMap$MergeSubscriber.onNext(FlowableFlatMap.java:163)
        at io.reactivex.internal.operators.flowable.FlowableMap$MapSubscriber.onNext(FlowableMap.java:68)
        at io.reactivex.internal.operators.flowable.FlowableObserveOn$ObserveOnSubscriber.runAsync(FlowableObserveOn.java:407)
        at io.reactivex.internal.operators.flowable.FlowableObserveOn$BaseObserveOnSubscriber.run(FlowableObserveOn.java:176)
        at io.reactivex.internal.schedulers.ExecutorScheduler$ExecutorWorker$BooleanRunnable.run(ExecutorScheduler.java:288)
        at io.reactivex.internal.schedulers.ExecutorScheduler$ExecutorWorker.run(ExecutorScheduler.java:253)
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1167)
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:641)
        at java.lang.Thread.run(Thread.java:919)
2019-12-27 18:55:16.848 E/Kuroba-dev | APP: 	Caused by: com.github.adamantcheese.chan.core.cache.downloader.FileCacheException$CancellationException: CancellationException for request with url = https://i.4cdn.org/g/1577462011089.gif, state = Canceled
        at com.github.adamantcheese.chan.core.cache.downloader.ConcurrentChunkedFileDownloader$downloadChunk$3$1.onFailure(ConcurrentChunkedFileDownloader.kt:522)
        at okhttp3.RealCall$AsyncCall.run(RealCall.kt:144)
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1167)
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:641)
        at java.lang.Thread.run(Thread.java:919)
      ComposedException 2 :
    	com.github.adamantcheese.chan.core.cache.downloader.FileCacheException$CancellationException: CancellationException for request with url = https://i.4cdn.org/g/1577462011089.gif, state = Canceled
        at com.github.adamantcheese.chan.core.cache.downloader.ConcurrentChunkedFileDownloader$downloadChunk$3$1.onFailure(ConcurrentChunkedFileDownloader.kt:522)
        at okhttp3.RealCall$AsyncCall.run(RealCall.kt:144)
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1167)
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:641)
        at java.lang.Thread.run(Thread.java:919)
```

Fixed.

**Comment by K1rakishou** [comment]
```
    Process: com.github.adamantcheese.chan.dev, PID: 27041
    java.lang.RuntimeException: This shouldn't be handled here!
        at com.github.adamantcheese.chan.core.cache.FileCacheV2$handleResults$7.invoke(FileCacheV2.kt:657)
        at com.github.adamantcheese.chan.core.cache.FileCacheV2$handleResults$7.invoke(FileCacheV2.kt:40)
        at com.github.adamantcheese.chan.core.cache.FileCacheV2$resultHandler$1$1.run(FileCacheV2.kt:713)
        at android.os.Handler.handleCallback(Handler.java:883)
        at android.os.Handler.dispatchMessage(Handler.java:100)
        at android.os.Looper.loop(Looper.java:214)
        at android.app.ActivityThread.main(ActivityThread.java:7356)
        at java.lang.reflect.Method.invoke(Native Method)
        at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:492)
        at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:930)
2019-12-31 11:56:38.146 E/Kuroba-dev | UNCAUGHT: java.lang.RuntimeException: This shouldn't be handled here!
        at com.github.adamantcheese.chan.core.cache.FileCacheV2$handleResults$7.invoke(FileCacheV2.kt:657)
        at com.github.adamantcheese.chan.core.cache.FileCacheV2$handleResults$7.invoke(FileCacheV2.kt:40)
        at com.github.adamantcheese.chan.core.cache.FileCacheV2$resultHandler$1$1.run(FileCacheV2.kt:713)
        at android.os.Handler.handleCallback(Handler.java:883)
        at android.os.Handler.dispatchMessage(Handler.java:100)
        at android.os.Looper.loop(Looper.java:214)
        at android.app.ActivityThread.main(ActivityThread.java:7356)
        at java.lang.reflect.Method.invoke(Native Method)
        at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:492)
        at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:930)
```

Fixed.

File: Kuroba/app/src/main/java/com/github/adamantcheese/chan/utils/ChanUtils.kt (hunk 3 above)
Comment (K1rakishou) [reply Kuroba/app/src/main/java/com/github/adamantcheese/chan/utils/ChanUtils.kt]: Done.

**Comment by K1rakishou** [comment]
Alright, all that shit from above is fixed but it's still not ready.

**Comment by K1rakishou** [comment]
It's done.

**Comment by K1rakishou** [comment]
~~I just had a really strange bug, it was like I downloaded a bunch of random bytes instead of an image. Gonna investigate it a little bit.~~
Fucking fixed.

**Comment by K1rakishou** [comment]
Alright, the stupid bug is fixed, should be good now.

**Comment by K1rakishou** [comment]
There is a new bug with webm streaming not working sometimes when opening a webm by swiping in the gallery gonna fix it tomorrow. Other than this everything else seems fine.

**Comment by TacoTheDank** [comment]
@K1rakishou We don't deserve you, man. Thanks for all the work you do :)

**Comment by K1rakishou** [comment]
Alright, all webm streaming related issues have been fixed. It's good to go now.

File: Kuroba/app/src/main/java/com/github/adamantcheese/chan/core/cache/downloader/PartialContentSupportChecker.kt [hunk 14]
```diff
@@ -0,0 +1,271 @@
...
+        val fileSize = activeDownloads.get(url)?.extraInfo?.fileSize ?: -1L
+        if (fileSize > 0) {
+            val host = url.toHttpUrlOrNull()?.host
+
+            if (host != null) {
+                val supportsPartialContent = synchronized(checkedChanHosts) {
+                    checkedChanHosts[host] ?: false
+                }
+
+                if (supportsPartialContent) {
```
Comment (K1rakishou) [inline Kuroba/app/src/main/java/com/github/adamantcheese/chan/core/cache/downloader/PartialContentSupportChecker.kt]: I think I forgot to handle the case when supportsPartialContent == false. In such case we don't want to send HEAD request because we already know that this site does not support PartialContent - there is no point. So we should return immediately as well with supportsPartialContentDownload == false.

File: Kuroba/app/src/main/java/com/github/adamantcheese/chan/core/cache/downloader/PartialContentSupportChecker.kt [hunk 15]
```diff
@@ -0,0 +1,271 @@
...
+            return Single.just(PartialContentCheckResult(false))
+        }
+
+        val fileSize = activeDownloads.get(url)?.extraInfo?.fileSize ?: -1L
+        if (fileSize > 0) {
+            val host = url.toHttpUrlOrNull()?.host
+
+            if (host != null) {
+                val supportsPartialContent = synchronized(checkedChanHosts) {
+                    checkedChanHosts[host] ?: false
```
Comment (K1rakishou) [inline Kuroba/app/src/main/java/com/github/adamantcheese/chan/core/cache/downloader/PartialContentSupportChecker.kt]: I should also separately check whether we have this chan in checkedChanHosts. I shouldn't assume that checkedChanHosts[host] == null is the same as supportsPartialContent == false.

File: Kuroba/app/src/main/java/com/github/adamantcheese/chan/ui/view/MultiImageView.java [hunk 16]
```diff
@@ -423,12 +490,12 @@ private void setGifFile(File file) {
                 return;
             }
         } catch (IOException e) {
-            e.printStackTrace();
-            onError();
+            Logger.e(TAG, "Error while trying to set a get file", e);
```
Comment (K1rakishou) [inline Kuroba/app/src/main/java/com/github/adamantcheese/chan/ui/view/MultiImageView.java]: gif image

File: Kuroba/app/src/main/java/com/github/adamantcheese/chan/ui/view/MultiImageView.java [hunk 17]
```diff
@@ -423,12 +490,12 @@ private void setGifFile(File file) {
...
+            onError(e);
             return;
         } catch (OutOfMemoryError e) {
             Runtime.getRuntime().gc();
-            e.printStackTrace();
+            Logger.e(TAG, "OOM while trying to set a get file", e);
```
Comment (K1rakishou) [inline Kuroba/app/src/main/java/com/github/adamantcheese/chan/ui/view/MultiImageView.java]: gif image

**Comment by Adamantcheese** [comment]
I'll write some review notes, but as more of a general thing, do you think it would be a good idea to break out the concurrent chunked downloading to its own repository like you did for SAF?

File: Kuroba/app/src/main/java/com/github/adamantcheese/chan/core/manager/UpdateManager.java [hunk 18]
```diff
@@ -256,41 +267,70 @@ private boolean processUpdateApiResponse(UpdateApiRequest.UpdateApiResponse resp
...
             @Override
-            public void onSuccess(RawFile file) {
+            public void onSuccess(AbstractFile file) {
                 BackgroundUtils.ensureMainThread();
 
                 updateDownloadDialog.dismiss();
                 updateDownloadDialog = null;
+
+                // We need to remove all the dots from the file name because FSAF won't allow that.
+                String fileName = StringUtils.dirNameRemoveBadCharacters(
```
Comment (Adamantcheese) [inline Kuroba/app/src/main/java/com/github/adamantcheese/chan/core/manager/UpdateManager.java]: You keep doing this everywhere, but I'm wondering if replacing periods with %2E would just work. That way the only actual period left in the URI is the last one specifying the file extension. Same thing for any other special characters. It doesn't make any sense that SAF can't deal with special characters, that would basically break everything that normal people would do (notably spaces in filenames).

File: Kuroba/app/src/main/java/com/github/adamantcheese/chan/core/manager/UpdateManager.java [hunk 19]
```diff
@@ -256,41 +267,70 @@ private boolean processUpdateApiResponse(UpdateApiRequest.UpdateApiResponse resp
...
-            public void onProgress(long downloaded, long total) {
+            public void onProgress(int chunkIndex, long downloaded, long total) {
                 BackgroundUtils.ensureMainThread();
 
                 updateDownloadDialog.setProgress((int) (updateDownloadDialog.getMax() * (downloaded / (double) total)));
             }
 
             @Override
-            public void onSuccess(RawFile file) {
+            public void onSuccess(AbstractFile file) {
```
Comment (Adamantcheese) [inline Kuroba/app/src/main/java/com/github/adamantcheese/chan/core/manager/UpdateManager.java]: If this method receives anything other than a RawFile instance, your file cache is not working properly. File caches should NEVER be on anything other than on-board storage, to prevent fast degradation of storage media.

File: Kuroba/app/src/main/java/com/github/adamantcheese/chan/core/di/NetModule.java [hunk 20]
```diff
@@ -19,28 +19,39 @@
...
 
 public class NetModule {
     public static final String USER_AGENT = getApplicationLabel() + "/" + BuildConfig.VERSION_NAME;
+    public static final long DOWNLOADER_OKHTTP_TIMEOUT_SECONDS = 20L;
+    public static final long PROXIED_OKHTTP_TIMEOUT_SECONDS = 30L;
+    public static final long THREAD_SAVE_MANAGER_OKHTTP_TIMEOUT_SECONDS = 30L;
+    public static final String THREAD_SAVE_MANAGER_OKHTTP_CLIENT_NAME = "thread_save_manager_okhttp_client";
+    public static final String DOWNLOADER_OKHTTP_CLIENT_NAME = "downloader_okhttp_client";
+    private static final String FILE_CACHE_DIR = "filecache";
+    private static final String FILE_CHUNKS_CACHE_DIR = "file_chunks_cache";
```
Comment (Adamantcheese) [inline Kuroba/app/src/main/java/com/github/adamantcheese/chan/core/di/NetModule.java:55]: This value should correspond to something in res/xml/file_paths.xml probably, so that Android knows how to deal with files stored in this directory.

File: Kuroba/app/src/main/java/com/github/adamantcheese/chan/core/cache/downloader/PartialContentSupportChecker.kt [hunk 21]
```diff
@@ -0,0 +1,288 @@
...
+    }
+
+    companion object {
+        private const val TAG = "PartialContentSupportChecker"
+        private const val ACCEPT_RANGES_HEADER = "Accept-Ranges"
+        private const val CONTENT_LENGTH_HEADER = "Content-Length"
+        private const val CF_CACHE_STATUS_HEADER = "CF-Cache-Status"
+        private const val ACCEPT_RANGES_HEADER_VALUE = "bytes"
+
+        private const val NOT_FOUND_STATUS_CODE = 404
```
Comment (Adamantcheese) [inline Kuroba/app/src/main/java/com/github/adamantcheese/chan/core/cache/downloader/PartialContentSupportChecker.kt]: You can just inline this field. It's only used in one other place in this file.

File: Kuroba/app/src/main/java/com/github/adamantcheese/chan/core/cache/downloader/ChunkPersister.kt [hunk 22]
```diff
@@ -0,0 +1,295 @@
...
+
+    private fun deleteChunkFile(chunkFile: RawFile) {
+        if (!fileManager.delete(chunkFile)) {
+            logError(TAG, "Couldn't delete chunk file: ${chunkFile.getFullPath()}")
+        }
+    }
+
+    companion object {
+        private const val TAG = "ChunkReader"
+        private const val NOT_FOUND_STATUS_CODE = 404
```
Comment (Adamantcheese) [inline Kuroba/app/src/main/java/com/github/adamantcheese/chan/core/cache/downloader/ChunkPersister.kt]: You can just inline this field. It's only used in one other place in this file.

File: Kuroba/app/src/main/java/com/github/adamantcheese/chan/core/cache/CacheHandler.kt [hunk 23]
```diff
@@ -0,0 +1,894 @@
...
+        if (directoryFiles.size <= 2) {
+            return
+        }
+
+        Logger.d(TAG, "trim() started")
+
+        // LastModified doesn't work on some platforms/phones
+        // (https://issuetracker.google.com/issues/36930892)
+        // so we have to use a workaround. When creating a cache file for a download we also create a
+        // meta file where we will put some info about this download: the main file creation time and
```
Comment (Adamantcheese) [inline Kuroba/app/src/main/java/com/github/adamantcheese/chan/core/cache/CacheHandler.kt:675]: From what I can tell, file creation time is correct, and lastModified should return the file creation time anyways, as there shouldn't be any modifications done to the file after it's fully downloaded. You might be able to get away with just keeping track of if a file was fully downloaded, which would make this whole thing a lot simpler (have a file for if the other file isn't complete, no extra file if the file completed successfully).

File: Kuroba/app/src/main/java/com/github/adamantcheese/chan/core/model/ChanThread.java [hunk 24]
```diff
@@ -18,18 +18,24 @@
...
 import com.github.adamantcheese.chan.core.model.orm.Loadable;
 
-import java.util.ArrayList;
+import java.util.Collections;
 import java.util.List;
 
 public class ChanThread {
     private Loadable loadable;
     private List<Post> posts;
+    // Unmodifiable list of posts. We need it to make this class "thread-safe" (it's actually
```
Comment (Adamantcheese) [inline Kuroba/app/src/main/java/com/github/adamantcheese/chan/core/model/ChanThread.java:27]: Is there any reason why we need posts to be thread-safe? Once everything is parsed into Post objects, they shouldn't be modified anymore anyways; the setNewPosts method below takes care of updating the post list anyways, so you did miss that, as your unmodifiable collection should also be updated down there.

File: Kuroba/app/src/main/java/com/github/adamantcheese/chan/core/presenter/ImageViewerPresenter.java [hunk 25]
```diff
@@ -83,14 +106,27 @@ public ImageViewerPresenter(Callback callback) {
...
         this.images = images;
-        selectedPosition = Math.max(0, Math.min(images.size() - 1, position));
         this.loadable = loadable;
+        this.selectedPosition = Math.max(0, Math.min(images.size() - 1, position));
+        this.progress = new HashMap<>(images.size());
 
-        progress = new ArrayList<>(images.size());
-        for (int i = 0; i < images.size(); i++) {
-            progress.add(i, -1f);
+        int chunksCount = ChanSettings.ConcurrentFileDownloadingChunks.toChunkCount(
```
Comment (Adamantcheese) [inline Kuroba/app/src/main/java/com/github/adamantcheese/chan/core/presenter/ImageViewerPresenter.java:111]: Surely there's a better way of writing this, it should be a simple parseInt or something.

File: Kuroba/app/src/main/java/com/github/adamantcheese/chan/core/presenter/ImageViewerPresenter.java [hunk 26]
```diff
@@ -432,6 +627,29 @@ private void setTitle(PostImage postImage, int position) {
...
+            showToast("Can't force reload because couldn't delete cached image");
+            return false;
+        }
+
+        callback.setImageMode(currentImage, LOWRES, false);
+        return true;
+    }
+
+    private enum SwipeDirection {
+        Default,
```
Comment (Adamantcheese) [inline Kuroba/app/src/main/java/com/github/adamantcheese/chan/core/presenter/ImageViewerPresenter.java:653]: Do we need a default swipe direction? Surely we can just have forward and backward, with forward being the default.

File: Kuroba/app/src/main/java/com/github/adamantcheese/chan/core/presenter/ThreadPresenter.java [hunk 27]
```diff
@@ -531,24 +558,35 @@ public void onChanLoaderData(ChanThread result) {
             }
 
             if (ChanSettings.autoLoadThreadImages.get() && !loadable.isLocal()) {
-                FileCache cache = instance(FileCache.class);
-                for (Post p : result.getPostsUnsafe()) {
+                List<PostImage> postImageList = new ArrayList<>(16);
```
Comment (Adamantcheese) [inline Kuroba/app/src/main/java/com/github/adamantcheese/chan/core/presenter/ThreadPresenter.java:561]: Any reason for the 16? I think it defaults to 10 anyways.

File: Kuroba/app/src/main/java/com/github/adamantcheese/chan/core/saver/ImageSaveTask.java [hunk 28]
```diff
@@ -100,45 +107,65 @@ public boolean getShare() {
...
+        imageSaveTaskAsyncResult.onError(exception);
     }
 
     @Override
     public void onEnd() {
         BackgroundUtils.ensureMainThread();
 
-        postFinished(success);
+        if (success) {
+            imageSaveTaskAsyncResult.onSuccess(ImageSaver.BundledDownloadResult.Success);
```
Comment (Adamantcheese) [inline Kuroba/app/src/main/java/com/github/adamantcheese/chan/core/saver/ImageSaveTask.java]: Could probably use some static imports here and just use `imageSaveTaskAsyncResult.onSuccess(success ? Success : Failure)`.

File: Kuroba/app/src/test/java/com/github/adamantcheese/chan/core/cache/CacheHandlerTest.kt [hunk 29]
```diff
@@ -0,0 +1,90 @@
+package com.github.adamantcheese.chan.core.cache
```
Comment (Adamantcheese) [inline Kuroba/app/src/test/java/com/github/adamantcheese/chan/core/cache/CacheHandlerTest.kt:1]: Move all your test classes to a single directory outside the main application files if you're going to keep them.

File: Kuroba/app/src/main/res/values/strings.xml [hunk 30]
```diff
@@ -754,4 +759,11 @@ Don't have a 4chan Pass?<br>
     <string name="image_saver_could_not_figure_out_save_location">Couldn\'t figure out save location</string>
     <string name="settings_captcha_setup">Captcha Settings</string>
     <string name="settings_captcha_setup_description">Captcha settings are per-site configurable. Tap for site setup.</string>
+    <string name="settings_concurrent_file_downloading_chunks_count_description">Split images/gifs/webms into chunks and download them concurrently (When it\'s possible. It doesn\'t work with 4chan servers, only when the file is cached by the cloudflare) to make the loading times shorter when viewing them in the gallery.\n\nHow many chunks a file will be split into:</string>
```
Comment (Adamantcheese) [inline Kuroba/app/src/main/res/values/strings.xml]: `Split file downloads into chunks and download them concurrently, when possible; makes loading times shorter when viewing them in the gallery.\n\nHow many chunks a file will be split into:` should be a better setting text. The user really doesn't care about intricacies like that. Also this setting text implies the "chunk" text, so your enum of settings just needs to be an IntegerSetting really.

File: Kuroba/app/src/main/res/values/strings.xml [hunk 31]
```diff
@@ -552,7 +556,8 @@ Tap the toolbar menu to change its color."
     </string>
     <string name="setting_theme_accent">Tap here to change the FAB color.</string>
     <string name="settings_open_logs">View logs</string>
-
+    <string name="settings_enable_verbose_logs">Enable verbose logs</string>
```
Comment (Adamantcheese) [inline Kuroba/app/src/main/res/values/strings.xml:558]: You might want to better explain what "verbose logs" means, because as far as I can tell it only applies to chunked file downloads only? It's too broad basically.

File: Kuroba/app/src/main/res/values/strings.xml [hunk 32]
```diff
@@ -134,6 +135,7 @@ Re-enable this permission in the app settings if you permanently disabled it."</
     <string name="action_download_album">Download album</string>
     <string name="action_transparency_toggle">Toggle opacity</string>
     <string name="action_image_rotate">Rotate image</string>
+    <string name="action_reload_file">Force reload</string>
```
Comment (Adamantcheese) [inline Kuroba/app/src/main/res/values/strings.xml]: We've already got a reload string, just use that. Two actually, one for captcha that should probably be removed to use the other one.

File: Kuroba/app/src/main/java/com/github/adamantcheese/chan/ui/widget/CancellableToast.kt [hunk 33]
```diff
@@ -0,0 +1,61 @@
+package com.github.adamantcheese.chan.ui.widget
```
Comment (Adamantcheese) [inline Kuroba/app/src/main/java/com/github/adamantcheese/chan/ui/widget/CancellableToast.kt:1]: I'm not entirely sure of the purpose of this class? If you display a toast while one is already being displayed, the previous one will be automatically hidden by the Toast's internal methods. You can see that code here https://android.googlesource.com/platform/frameworks/base/+/f4bed684c939b0f8809ef404b8609fe4ef849263/core/java/android/widget/Toast.java#426

Comment (Adamantcheese) [reply Kuroba/app/src/main/java/com/github/adamantcheese/chan/ui/widget/CancellableToast.kt:1]: You can also test it for yourself by putting this code snippet into the onCreate method in StartActivity. ```BackgroundUtils.runOnUiThread(() -> BackgroundUtils.runWithExecutor(Executors.newSingleThreadExecutor(), () -> {
            Random r = new Random();
            while (true) {
                showToast(String.valueOf(r.nextInt()));
                long time = System.currentTimeMillis();
                while (System.currentTimeMillis() - time < 1000) {}
            }
        }), 10000);```

File: Kuroba/app/src/main/java/com/github/adamantcheese/chan/ui/helper/ImagePickDelegate.java [hunk 34]
```diff
@@ -87,33 +96,66 @@ public void pick(ImagePickCallback callback, boolean longPressed) {
                 try {
                     clipboardURL =
                             HttpUrl.get(getClipboardManager().getPrimaryClip().getItemAt(0).getText().toString());
-                } catch (Exception ignored) {
-                    showToast(R.string.image_url_get_failed);
+                } catch (Exception exception) {
+                    String message = getAppContext().getString(
```
Comment (Adamantcheese) [inline Kuroba/app/src/main/java/com/github/adamantcheese/chan/ui/helper/ImagePickDelegate.java:100]: You've got this sort of method call everywhere, instead of just using getString directly from AndroidUtils. I added those utility methods for a reason!

File: Kuroba/app/src/main/java/com/github/adamantcheese/chan/ui/toolbar/ToolbarMenuItem.java [hunk 35]
```diff
@@ -112,6 +112,22 @@ public void setVisible(boolean visible) {
...
     }
 
+    public void setEnabled(boolean enabled) {
+        this.enabled = enabled;
+
+        if (view != null) {
+            if (!enabled) {
+                view.setClickable(false);
+                view.setFocusable(false);
+                view.setAlpha(.5f);
```
Comment (Adamantcheese) [inline Kuroba/app/src/main/java/com/github/adamantcheese/chan/ui/toolbar/ToolbarMenuItem.java]: I had it tinting to grey before, because for certain themes, just changing the alpha may make it look sorta bad.

File: Kuroba/app/src/main/java/com/github/adamantcheese/chan/ui/controller/AlbumDownloadController.java [hunk 36]
```diff
@@ -152,6 +171,43 @@ private void handleDownloadResult(List<ImageSaveTask> tasks) {
...
+
+    @Override
+    public void onBundleDownloadCompleted() {
+        BackgroundUtils.ensureMainThread();
+
+        if (loadingViewController == null) {
+            throw new IllegalStateException("LoadingViewController is not set!");
+        }
+
+        if (!loadingViewController.shown) {
```
Comment (Adamantcheese) [inline Kuroba/app/src/main/java/com/github/adamantcheese/chan/ui/controller/AlbumDownloadController.java:198]: Doesn't really matter if the controller is being shown or not because we're getting rid of it anyways. This code can be removed.

File: Kuroba/app/src/main/java/com/github/adamantcheese/chan/core/settings/ChanSettings.java [hunk 37]
```diff
@@ -109,6 +109,36 @@ public String getKey() {
         }
     }
 
+    public enum ConcurrentFileDownloadingChunks implements OptionSettingItem {
+        One("One chunk"),
```
Comment (Adamantcheese) [inline Kuroba/app/src/main/java/com/github/adamantcheese/chan/core/settings/ChanSettings.java:113]: I mention this elsewhere, but you might be able to just use a IntegerSetting for this instead, with a callback to snap it to a multiple of 2, with some maximum.

File: Kuroba/app/src/main/java/com/github/adamantcheese/chan/core/cache/FileCacheV2.kt [hunk 38]
```diff
@@ -0,0 +1,944 @@
...
+                })
+    }
+
+    fun isRunning(url: String): Boolean {
+        return synchronized(activeDownloads) {
+            activeDownloads.getState(url) == DownloadState.Running
+        }
+    }
+
+    fun enqueueMediaPrefetchRequestBatch(
```
Comment (Adamantcheese) [inline Kuroba/app/src/main/java/com/github/adamantcheese/chan/core/cache/FileCacheV2.kt:210]: This method isn't specific to media prefetching, just call it enqueueRequestBatch.

File: Kuroba/app/src/main/java/com/github/adamantcheese/chan/core/cache/downloader/Logging.kt [hunk 39]
```diff
@@ -0,0 +1,15 @@
+package com.github.adamantcheese.chan.core.cache.downloader
```
Comment (Adamantcheese) [inline Kuroba/app/src/main/java/com/github/adamantcheese/chan/core/cache/downloader/Logging.kt:1]: You can toss these functions into the Logger class directly, no need for another logging class.

File: Kuroba/app/src/main/java/com/github/adamantcheese/chan/core/cache/downloader/PartialContentSupportChecker.kt [hunk 40]
```diff
@@ -0,0 +1,288 @@
...
+internal class PartialContentSupportChecker(
+        private val okHttpClient: OkHttpClient,
+        private val activeDownloads: ActiveDownloads,
+        private val maxTimeoutMs: Long
+) {
+    // Thread safe
+    private val cachedResults = LruCache<String, PartialContentCheckResult>(1024)
+    @GuardedBy("itself")
+    private val checkedChanHosts = mutableMapOf<String, Boolean>()
+    private val badSites = setOf(
```
Comment (Adamantcheese) [inline Kuroba/app/src/main/java/com/github/adamantcheese/chan/core/cache/downloader/PartialContentSupportChecker.kt]: I dunno if this is the best way of dealing with "bad" sites.

**Review by Adamantcheese — CHANGES_REQUESTED** [review]
There's probably more that I missed, but I guess it's a start?

File: Kuroba/app/src/main/java/com/github/adamantcheese/chan/core/presenter/ImageViewerPresenter.java (hunk 26 above)
Comment (K1rakishou) [reply Kuroba/app/src/main/java/com/github/adamantcheese/chan/core/presenter/ImageViewerPresenter.java:653]: Yeah, we need Default state that does nothing (or it probably should be renamed as NoDirection) because when we open an image by clicking it we don't want to preload any other image and that's why we need the third state - Default in this case.

File: Kuroba/app/src/main/res/values/strings.xml (hunk 31 above)
Comment (K1rakishou) [reply Kuroba/app/src/main/res/values/strings.xml:558]: Right now yes, only for chunked file downloads. But I could also use it for ThreadSaveManager because it kinda spams logs too.

File: Kuroba/app/src/main/java/com/github/adamantcheese/chan/core/presenter/ImageViewerPresenter.java (hunk 26 above)
Comment (Adamantcheese) [reply Kuroba/app/src/main/java/com/github/adamantcheese/chan/core/presenter/ImageViewerPresenter.java:653]: Right, but what I mean is that generally the user will start swiping forward, so the default state seems pointless.

File: Kuroba/app/src/main/res/values/strings.xml (hunk 32 above)
Comment (K1rakishou) [reply Kuroba/app/src/main/res/values/strings.xml]: Well, I called it "Force reload" because the cache file will be removed ahead of time from the disk. So it kinda feels like a forced operation.

File: Kuroba/app/src/main/java/com/github/adamantcheese/chan/ui/widget/CancellableToast.kt (hunk 33 above)
Comment (K1rakishou) [reply Kuroba/app/src/main/java/com/github/adamantcheese/chan/ui/widget/CancellableToast.kt:1]: Well it isn't removed. It's just queued up with other toasts and they all are being shown at the same time. That's why Floens did that too but it wasn't extracted into a separate class.

File: Kuroba/app/src/main/java/com/github/adamantcheese/chan/ui/helper/ImagePickDelegate.java (hunk 34 above)
Comment (K1rakishou) [reply Kuroba/app/src/main/java/com/github/adamantcheese/chan/ui/helper/ImagePickDelegate.java:100]: Yeah, just a habit.

File: Kuroba/app/src/main/java/com/github/adamantcheese/chan/ui/toolbar/ToolbarMenuItem.java (hunk 35 above)
Comment (K1rakishou) [reply Kuroba/app/src/main/java/com/github/adamantcheese/chan/ui/toolbar/ToolbarMenuItem.java]: Yeah I noticed it too on my real device. But on emulator it works fine, Strange.

File: Kuroba/app/src/main/java/com/github/adamantcheese/chan/ui/controller/AlbumDownloadController.java (hunk 36 above)
Comment (K1rakishou) [reply Kuroba/app/src/main/java/com/github/adamantcheese/chan/ui/controller/AlbumDownloadController.java:198]: It's in case if someone else adds something new that may conflict with the current logic. it's future-proofing.

File: Kuroba/app/src/main/java/com/github/adamantcheese/chan/core/cache/downloader/Logging.kt (hunk 39 above)
Comment (K1rakishou) [reply Kuroba/app/src/main/java/com/github/adamantcheese/chan/core/cache/downloader/Logging.kt:1]: Nah, I wanted it this way specifically so it prints the current thread it is executed on. We may not want it in other places. They are internal for that package so you won't be able to use them in any other places of the project.

File: Kuroba/app/src/main/java/com/github/adamantcheese/chan/core/cache/downloader/PartialContentSupportChecker.kt (hunk 40 above)
Comment (K1rakishou) [reply Kuroba/app/src/main/java/com/github/adamantcheese/chan/core/cache/downloader/PartialContentSupportChecker.kt]: 2ch.hk sends file size in KBs instead of bytes which makes it impossible to calculate the exact file size which breaks chunking. But yeah, maybe it should be in resources or something?

Comment (K1rakishou) [reply Kuroba/app/src/main/java/com/github/adamantcheese/chan/core/cache/downloader/PartialContentSupportChecker.kt]: And it probably should be called something like "unsupported sites"? Or, "sites that send incorrect file size"?

**Comment by K1rakishou** [comment]
@Adamantcheese 

>do you think it would be a good idea to break out the concurrent chunked downloading to its own repository like you did for SAF?

Nah, I only did it with FSAF because I thought it would be a good idea to make it into a separate library because SAF is a pain in the ass and some other people might use it. This one, on the other hand, is very specific for our app. You won't see stuff like this in any other regular app. 

But, I could extract it into a separate module since everything is already internal to it's package.

File: Kuroba/app/src/main/java/com/github/adamantcheese/chan/core/model/ChanThread.java (hunk 24 above)
Comment (K1rakishou) [reply Kuroba/app/src/main/java/com/github/adamantcheese/chan/core/model/ChanThread.java:27]: No. If you take a look at how UnmodifiableList is implemented you will see that the only thing it does is it stores internally a reference to the list you provide to it and uses it when you do operations like get/indexOf etc or throws an exception if you try to call any method that modifies a list (add/remove). So if you update the original collection the unmodifiableList is updated too. That's why you don't need to update unmodifiableList (moreover you won't be able to because it will throw an exception). 

You just need to make sure that the original reference is not changed and if it is then you need to create a new unmodifiableList.

Comment (K1rakishou) [reply Kuroba/app/src/main/java/com/github/adamantcheese/chan/core/model/ChanThread.java:27]: >Is there any reason why we need posts to be thread-safe?

Haven't we had bugs because of posts being accessed from multiple threads? Or was it loadable? In any case, those posts, at the very least, are being accessed from multiple threads.

File: Kuroba/app/src/main/java/com/github/adamantcheese/chan/core/presenter/ImageViewerPresenter.java (hunk 26 above)
Comment (K1rakishou) [reply Kuroba/app/src/main/java/com/github/adamantcheese/chan/core/presenter/ImageViewerPresenter.java:653]: Well can't know for sure. The user may start swiping backwards too. But once he swipes in either direction we can assume that he will continue swiping in that direction and start doing the preloading.

Comment (K1rakishou) [reply Kuroba/app/src/main/java/com/github/adamantcheese/chan/core/presenter/ImageViewerPresenter.java:653]: And one more reason why I did it like that is because preloading spams the logs and it's hard to see logs for the image you clicked (the one you care about) and not the one that is preloading.

File: Kuroba/app/src/main/java/com/github/adamantcheese/chan/core/presenter/ThreadPresenter.java (hunk 27 above)
Comment (K1rakishou) [reply Kuroba/app/src/main/java/com/github/adamantcheese/chan/core/presenter/ThreadPresenter.java:561]: 16 is a power of two, haha. Should probably just count how many posts with images there are and use that number.

File: Kuroba/app/src/test/java/com/github/adamantcheese/chan/core/cache/CacheHandlerTest.kt (hunk 29 above)
Comment (K1rakishou) [reply Kuroba/app/src/test/java/com/github/adamantcheese/chan/core/cache/CacheHandlerTest.kt:1]: Can you elaborate, please? I don't really get what you want me to do here. They are already in a signle directory (Kuroba/app/src/test)

File: Kuroba/app/src/main/java/com/github/adamantcheese/chan/core/manager/UpdateManager.java (hunk 18 above)
Comment (K1rakishou) [reply Kuroba/app/src/main/java/com/github/adamantcheese/chan/core/manager/UpdateManager.java]: But isn't any other app does the same? Like NewPipe does for example (https://github.com/TeamNewPipe/NewPipe/blob/38b0b79644abc9ef9efdee92fe5380e0f8117e0e/app/src/main/java/org/schabi/newpipe/util/FilenameUtils.java#L22). 

I just don't get what's the point of having them. And this will surely break FSAF because I check for %2E too.

File: Kuroba/app/src/main/java/com/github/adamantcheese/chan/ui/widget/CancellableToast.kt (hunk 33 above)
Comment (K1rakishou) [reply Kuroba/app/src/main/java/com/github/adamantcheese/chan/ui/widget/CancellableToast.kt:1]: I guess the code in AOSP is correct but only for a single instance of Toast. Since Toast.makeText() returns a new instance every single time you call it, the previous one won't get canceled. And that's exactly why I implemented CancelableToast.

File: Kuroba/app/src/main/java/com/github/adamantcheese/chan/core/cache/downloader/PartialContentSupportChecker.kt (hunk 40 above)
Comment (K1rakishou) [reply Kuroba/app/src/main/java/com/github/adamantcheese/chan/core/cache/downloader/PartialContentSupportChecker.kt]: In any case, this doesn't mean that the whole concurrent chunked download won't work on 2ch.hk or other "bad sites". It just means that we can't trust the file size we get along with thread json from those sites and need to send HEAD request to such sites every time. So basically this optimisation won't work on those site, we will have to send HEAD request every time. 

Once there is another "bad site" I will think of how to make this thing more flexible.

File: Kuroba/app/src/main/java/com/github/adamantcheese/chan/core/manager/UpdateManager.java (hunk 18 above)
Comment (Adamantcheese) [reply Kuroba/app/src/main/java/com/github/adamantcheese/chan/core/manager/UpdateManager.java]: If the user selects CHARSET_MOST_SPECIAL in NewPipe, then periods are allowable in filenames. Either way, only RawFiles should ever be passed to this method. But I'm sure periods are allowable. By the way you don't check for %2E anywhere in your FSAF library, nor in Kuroba. I would recommend you add some tests in FSAF for those cases where periods are included in filenames.

File: Kuroba/app/src/main/java/com/github/adamantcheese/chan/ui/controller/AlbumDownloadController.java (hunk 36 above)
Comment (Adamantcheese) [reply Kuroba/app/src/main/java/com/github/adamantcheese/chan/ui/controller/AlbumDownloadController.java:198]: There's nothing to future-proof here. If you don't toss it out, I will.

File: Kuroba/app/src/main/java/com/github/adamantcheese/chan/ui/toolbar/ToolbarMenuItem.java (hunk 35 above)
Comment (Adamantcheese) [reply Kuroba/app/src/main/java/com/github/adamantcheese/chan/ui/toolbar/ToolbarMenuItem.java]: That's because #FFFFFFFF being tinted grey becomes #FF888888 versus alpha which is #88FFFFFF, which are blended completely differently with the background. Emulator or not the result should be the same.

File: Kuroba/app/src/main/java/com/github/adamantcheese/chan/ui/widget/CancellableToast.kt (hunk 33 above)
Comment (Adamantcheese) [reply Kuroba/app/src/main/java/com/github/adamantcheese/chan/ui/widget/CancellableToast.kt:1]: If you display a toast, and then immediately display another toast, what happens is that the first toast's view is detached from the window and then it is allowed for its timer to run out, while the second toast is displayed. So you'd prefer that, when you display a toast and then immediately display a second toast, that the first toast doesn't sit around and wait to be removed? There's barely any performance impact, and as far as I can tell, it's perfectly fine to spam Toast instances, as there's built-in protection for this kind of situation anyways https://android.googlesource.com/platform/frameworks/base/+/9a7debe5857ffc7c71cfc4082b1b6d72a5cf81cd/services/java/com/android/server/NotificationManagerService.java#694

File: Kuroba/app/src/main/res/values/strings.xml (hunk 32 above)
Comment (Adamantcheese) [reply Kuroba/app/src/main/res/values/strings.xml]: A manual reload is necessarily forced, kinda by definition.

File: Kuroba/app/src/main/java/com/github/adamantcheese/chan/core/presenter/ImageViewerPresenter.java (hunk 26 above)
Comment (Adamantcheese) [reply Kuroba/app/src/main/java/com/github/adamantcheese/chan/core/presenter/ImageViewerPresenter.java:653]: Right, but understand that the _USER_ doesn't give a shit about logs. The user cares about if things are working as they expect it to, which in this case probably means they'd expect the next image to be preloading, which is generally forward. It's a small change that improves UX and doesn't hurt too much if the user doesn't start swiping in the forward direction to start.

File: Kuroba/app/src/main/java/com/github/adamantcheese/chan/core/model/ChanThread.java (hunk 24 above)
Comment (Adamantcheese) [reply Kuroba/app/src/main/java/com/github/adamantcheese/chan/core/model/ChanThread.java:27]: Kinda garbage how that works around the whole "unmodifiable" principle. From what I can tell, posts itself can be unmodifiable and we won't need the extra read-only variable; the list is only ever read from, never written to.

File: Kuroba/app/src/main/java/com/github/adamantcheese/chan/core/manager/UpdateManager.java (hunk 18 above)
Comment (K1rakishou) [reply Kuroba/app/src/main/java/com/github/adamantcheese/chan/core/manager/UpdateManager.java]: >internal const val ENCODED_SEPARATOR = "%2F"

Yeah, I've mixed it up, I'm checking for different kinds of the slash symbol, not periods.

File: Kuroba/app/src/main/java/com/github/adamantcheese/chan/ui/controller/AlbumDownloadController.java (hunk 36 above)
Comment (K1rakishou) [reply Kuroba/app/src/main/java/com/github/adamantcheese/chan/ui/controller/AlbumDownloadController.java:198]: I still don't get why remove such checks. If you are concerned that it may blow up in release then I can just throw it only in dev builds. These checks are way better than weird bugs with invisible controllers blocking your input or controllers not showing up at all so I don't get the point of removing them.

File: Kuroba/app/src/main/java/com/github/adamantcheese/chan/core/cache/downloader/PartialContentSupportChecker.kt (hunk 40 above)
Comment (K1rakishou) [reply Kuroba/app/src/main/java/com/github/adamantcheese/chan/core/cache/downloader/PartialContentSupportChecker.kt]: I think I came up with an idea of where I should store this info. In classes that implement Site interface. Then I can just inject SiteRepository, and with it's help check if the current site is "bad".

File: Kuroba/app/src/main/java/com/github/adamantcheese/chan/core/model/ChanThread.java (hunk 24 above)
Comment (K1rakishou) [reply Kuroba/app/src/main/java/com/github/adamantcheese/chan/core/model/ChanThread.java:27]: Well the whole point of unmodifiable collections is to not allow to add new items to it. it's more like "read-only" collection.

>From what I can tell, posts itself can be unmodifiable and we won't need the extra read-only variable

Actually yes. I can just make the "posts" unmodifiable collection and that's should be enough.

File: Kuroba/app/src/main/java/com/github/adamantcheese/chan/core/presenter/ImageViewerPresenter.java (hunk 26 above)
Comment (K1rakishou) [reply Kuroba/app/src/main/java/com/github/adamantcheese/chan/core/presenter/ImageViewerPresenter.java:653]: It hurts if the user doesn't use swipes at all, only clicking at images and then clicking back. In such case we will be preloading images for nothing (For example, I don't really use swipes, I only ever used them to test this thing).

Maybe this can be made into a separate setting? Something like: "When clicking an image do you want to preload next/previous/both/none image(s)?"

File: Kuroba/app/src/main/res/values/strings.xml (hunk 32 above)
Comment (K1rakishou) [reply Kuroba/app/src/main/res/values/strings.xml]: Well, I guess so.

File: Kuroba/app/src/main/java/com/github/adamantcheese/chan/ui/widget/CancellableToast.kt (hunk 33 above)
Comment (K1rakishou) [reply Kuroba/app/src/main/java/com/github/adamantcheese/chan/ui/widget/CancellableToast.kt:1]: I should probably record a video and compare the two, because there is a noticeable difference.

File: Kuroba/app/src/main/java/com/github/adamantcheese/chan/ui/toolbar/ToolbarMenuItem.java (hunk 35 above)
Comment (K1rakishou) [reply Kuroba/app/src/main/java/com/github/adamantcheese/chan/ui/toolbar/ToolbarMenuItem.java]: Alright, I will use your implementation with tinting instead of using alpha.

File: Kuroba/app/src/main/java/com/github/adamantcheese/chan/core/manager/UpdateManager.java (hunk 19 above)
Comment (K1rakishou) [reply Kuroba/app/src/main/java/com/github/adamantcheese/chan/core/manager/UpdateManager.java]: I don't remember why I did that and apparently it's not even needed. I even had check that would throw an exception if a any file other than RawFile is passed there.

File: Kuroba/app/src/main/java/com/github/adamantcheese/chan/core/di/NetModule.java (hunk 20 above)
Comment (K1rakishou) [reply Kuroba/app/src/main/java/com/github/adamantcheese/chan/core/di/NetModule.java:55]: Done.

File: Kuroba/app/src/main/java/com/github/adamantcheese/chan/core/cache/downloader/PartialContentSupportChecker.kt (hunk 21 above)
Comment (K1rakishou) [reply Kuroba/app/src/main/java/com/github/adamantcheese/chan/core/cache/downloader/PartialContentSupportChecker.kt]: Done.

File: Kuroba/app/src/main/java/com/github/adamantcheese/chan/core/cache/downloader/ChunkPersister.kt (hunk 22 above)
Comment (K1rakishou) [reply Kuroba/app/src/main/java/com/github/adamantcheese/chan/core/cache/downloader/ChunkPersister.kt]: Done.

File: Kuroba/app/src/main/java/com/github/adamantcheese/chan/core/cache/CacheHandler.kt (hunk 23 above)
Comment (K1rakishou) [reply Kuroba/app/src/main/java/com/github/adamantcheese/chan/core/cache/CacheHandler.kt:675]: This won't work, I think. I store a  boolean flag in the meta file that I set to true once a download is completed, chunks are merged into a cache file and the cache file is verified (md5 hashes match). I can't do that without the meta file.

File: Kuroba/app/src/main/java/com/github/adamantcheese/chan/core/model/ChanThread.java (hunk 24 above)
Comment (K1rakishou) [reply Kuroba/app/src/main/java/com/github/adamantcheese/chan/core/model/ChanThread.java:27]: Done.

File: Kuroba/app/src/main/java/com/github/adamantcheese/chan/core/saver/ImageSaveTask.java (hunk 28 above)
Comment (K1rakishou) [reply Kuroba/app/src/main/java/com/github/adamantcheese/chan/core/saver/ImageSaveTask.java]: Done.

File: Kuroba/app/src/main/java/com/github/adamantcheese/chan/ui/toolbar/ToolbarMenuItem.java (hunk 35 above)
Comment (K1rakishou) [reply Kuroba/app/src/main/java/com/github/adamantcheese/chan/ui/toolbar/ToolbarMenuItem.java]: Done.

File: Kuroba/app/src/main/java/com/github/adamantcheese/chan/core/cache/FileCacheV2.kt (hunk 38 above)
Comment (K1rakishou) [reply Kuroba/app/src/main/java/com/github/adamantcheese/chan/core/cache/FileCacheV2.kt:210]: Well, actually, right now it's being used only for prefetching.

Comment (K1rakishou) [reply Kuroba/app/src/main/java/com/github/adamantcheese/chan/core/cache/FileCacheV2.kt:210]: For album downloads there is enqueueNormalDownloadFileRequest

File: Kuroba/app/src/main/res/values/strings.xml (hunk 30 above)
Comment (K1rakishou) [reply Kuroba/app/src/main/res/values/strings.xml]: Done.

File: Kuroba/app/src/main/java/com/github/adamantcheese/chan/core/settings/ChanSettings.java (hunk 37 above)
Comment (K1rakishou) [reply Kuroba/app/src/main/java/com/github/adamantcheese/chan/core/settings/ChanSettings.java:113]: I did it via ListSettingView because I didn't want the user to be able to enter the number by himself. I rewrote it a little bit so now it looks like similar setting - backgroundTimeout.

File: Kuroba/app/src/main/java/com/github/adamantcheese/chan/core/presenter/ImageViewerPresenter.java (hunk 25 above)
Comment (K1rakishou) [reply Kuroba/app/src/main/java/com/github/adamantcheese/chan/core/presenter/ImageViewerPresenter.java:111]: I did it via ListSettingView because I didn't want the user to be able to enter the number by himself. I rewrote it a little bit so now it looks like similar setting - backgroundTimeout.

File: Kuroba/app/src/main/java/com/github/adamantcheese/chan/ui/widget/CancellableToast.kt (hunk 33 above)
Comment (K1rakishou) [reply Kuroba/app/src/main/java/com/github/adamantcheese/chan/ui/widget/CancellableToast.kt:1]: Alright, here is how cancelable toast works: https://files.catbox.moe/szd4fr.mp4
and here is a regular toast: https://files.catbox.moe/l68ee6.mp4
The difference is pretty noticeable.

File: Kuroba/app/src/main/java/com/github/adamantcheese/chan/ui/helper/ImagePickDelegate.java (hunk 34 above)
Comment (K1rakishou) [reply Kuroba/app/src/main/java/com/github/adamantcheese/chan/ui/helper/ImagePickDelegate.java:100]: Done.

File: Kuroba/app/src/main/java/com/github/adamantcheese/chan/core/manager/UpdateManager.java (hunk 19 above)
Comment (K1rakishou) [reply Kuroba/app/src/main/java/com/github/adamantcheese/chan/core/manager/UpdateManager.java]: Done.

File: Kuroba/app/src/main/java/com/github/adamantcheese/chan/core/manager/UpdateManager.java (hunk 18 above)
Comment (K1rakishou) [reply Kuroba/app/src/main/java/com/github/adamantcheese/chan/core/manager/UpdateManager.java]: Not done yet. Gonna do this one tomorrow since it will take some time.

File: Kuroba/app/src/main/res/values/strings.xml (hunk 32 above)
Comment (K1rakishou) [reply Kuroba/app/src/main/res/values/strings.xml]: Done.

File: Kuroba/app/src/main/java/com/github/adamantcheese/chan/core/cache/downloader/PartialContentSupportChecker.kt (hunk 40 above)
Comment (K1rakishou) [reply Kuroba/app/src/main/java/com/github/adamantcheese/chan/core/cache/downloader/PartialContentSupportChecker.kt]: Gonna do this one tomorrow too.

File: Kuroba/app/src/main/java/com/github/adamantcheese/chan/core/cache/CacheHandler.kt (hunk 23 above)
Comment (Adamantcheese) [reply Kuroba/app/src/main/java/com/github/adamantcheese/chan/core/cache/CacheHandler.kt:675]: Right, what I mean is you can have an empty file be your meta file; if the meta file exists, that boolean isDownloaded flag is effectively false. If the meta file doesn't exist, the flag is true.

File: Kuroba/app/src/main/java/com/github/adamantcheese/chan/core/presenter/ImageViewerPresenter.java (hunk 26 above)
Comment (Adamantcheese) [reply Kuroba/app/src/main/java/com/github/adamantcheese/chan/core/presenter/ImageViewerPresenter.java:653]: I'd be alright with this being a setting, even if I think it's pointless. The default of the setting should be next/forward though, as most people use the image viewer in that manner.

File: Kuroba/app/src/main/java/com/github/adamantcheese/chan/core/presenter/ThreadPresenter.java (hunk 27 above)
Comment (Adamantcheese) [reply Kuroba/app/src/main/java/com/github/adamantcheese/chan/core/presenter/ThreadPresenter.java:561]: Eh, was just curious. No changes needed.

File: Kuroba/app/src/main/java/com/github/adamantcheese/chan/ui/widget/CancellableToast.kt (hunk 33 above)
Comment (Adamantcheese) [reply Kuroba/app/src/main/java/com/github/adamantcheese/chan/ui/widget/CancellableToast.kt:1]: Yeah, it is better I agree. Although now I'm wondering if we even need to bother with displaying toasts while doing a batch download? Maybe make that whole "Doing heavy lifting" dialog be a Snackbar instance instead and allow the user can cancel the download from it? You shouldn't need to block the UI while the download is going on in the background.

File: Kuroba/app/src/main/java/com/github/adamantcheese/chan/core/cache/FileCacheV2.kt (hunk 38 above)
Comment (Adamantcheese) [reply Kuroba/app/src/main/java/com/github/adamantcheese/chan/core/cache/FileCacheV2.kt:210]: Yeah, the way you did it makes sense with the architecture. Just feels weird that an album download operation isn't a "batch" operation like media prefetching, but that's because it's a batch of ImageSaveTask instances doing it one by one. No changes needed.

File: Kuroba/app/src/main/java/com/github/adamantcheese/chan/core/presenter/ImageViewerPresenter.java (hunk 25 above)
Comment (Adamantcheese) [reply Kuroba/app/src/main/java/com/github/adamantcheese/chan/core/presenter/ImageViewerPresenter.java:111]: Is there a reason you don't want the user to enter a chunk amount by themselves? You can add in some code to IntegerSettingView to limit the range of input values.

File: Kuroba/app/src/main/java/com/github/adamantcheese/chan/ui/controller/AlbumDownloadController.java (hunk 36 above)
Comment (Adamantcheese) [reply Kuroba/app/src/main/java/com/github/adamantcheese/chan/ui/controller/AlbumDownloadController.java:198]: The shown variable is basically only internal to the Controller class. It's literally not used anywhere else in the code and it has no effect on whether or not a controller is or is not destroyed. Shown or not, once you call stopPresenting, the shown state is changed to false and the controller is removed. I really should make that variable private.

File: Kuroba/app/src/main/java/com/github/adamantcheese/chan/core/presenter/ImageViewerPresenter.java (hunk 25 above)
Comment (K1rakishou) [reply Kuroba/app/src/main/java/com/github/adamantcheese/chan/core/presenter/ImageViewerPresenter.java:111]: After testing it for couple of weeks I can say that there is no point in splitting a file in more than 4 chunks. So 1, 2 and 4 should be enough. There is just no benefit after 4 chunks.

File: Kuroba/app/src/main/java/com/github/adamantcheese/chan/core/presenter/ImageViewerPresenter.java (hunk 26 above)
Comment (K1rakishou) [reply Kuroba/app/src/main/java/com/github/adamantcheese/chan/core/presenter/ImageViewerPresenter.java:653]: Alright.

File: Kuroba/app/src/main/java/com/github/adamantcheese/chan/ui/widget/CancellableToast.kt (hunk 33 above)
Comment (K1rakishou) [reply Kuroba/app/src/main/java/com/github/adamantcheese/chan/ui/widget/CancellableToast.kt:1]: Well, we will have to move the ImageSaver into a separate foreground service then because user may assume that the download should continue to work even if he closes the app.

File: Kuroba/app/src/main/java/com/github/adamantcheese/chan/ui/controller/AlbumDownloadController.java (hunk 36 above)
Comment (K1rakishou) [reply Kuroba/app/src/main/java/com/github/adamantcheese/chan/ui/controller/AlbumDownloadController.java:198]: >I really should make that variable private.

Yeah, probably. Well, in this case, yes, there is no point in this check.

File: Kuroba/app/src/main/java/com/github/adamantcheese/chan/core/presenter/ImageViewerPresenter.java (hunk 25 above)
Comment (Adamantcheese) [reply Kuroba/app/src/main/java/com/github/adamantcheese/chan/core/presenter/ImageViewerPresenter.java:111]: You didn't answer my question. Why would you not allow 3 chunks?

File: Kuroba/app/src/main/java/com/github/adamantcheese/chan/ui/widget/CancellableToast.kt (hunk 33 above)
Comment (K1rakishou) [reply Kuroba/app/src/main/java/com/github/adamantcheese/chan/ui/widget/CancellableToast.kt:1]: >Maybe make that whole "Doing heavy lifting" dialog be a Snackbar instance instead and allow the user can cancel the download from it? 

Oh yeah, and it's already possible to cancel it via notification.

File: Kuroba/app/src/main/java/com/github/adamantcheese/chan/core/presenter/ImageViewerPresenter.java (hunk 25 above)
Comment (K1rakishou) [reply Kuroba/app/src/main/java/com/github/adamantcheese/chan/core/presenter/ImageViewerPresenter.java:111]: Because it's not a power of two.

Comment (K1rakishou) [reply Kuroba/app/src/main/java/com/github/adamantcheese/chan/core/presenter/ImageViewerPresenter.java:111]: I mean, what's the point of having the user input a value if there are only three (well maybe four) possible options?

File: Kuroba/app/src/main/java/com/github/adamantcheese/chan/core/presenter/ImageViewerPresenter.java (hunk 26 above)
Comment (K1rakishou) [reply Kuroba/app/src/main/java/com/github/adamantcheese/chan/core/presenter/ImageViewerPresenter.java:653]: Done.

File: Kuroba/app/src/main/res/values/strings.xml (hunk 31 above)
Comment (K1rakishou) [reply Kuroba/app/src/main/res/values/strings.xml:558]: Done.

File: Kuroba/app/src/main/java/com/github/adamantcheese/chan/ui/controller/AlbumDownloadController.java (hunk 36 above)
Comment (K1rakishou) [reply Kuroba/app/src/main/java/com/github/adamantcheese/chan/ui/controller/AlbumDownloadController.java:198]: I guess I misinterpreted the whole point of this conversation because I for some reason thought you are talking about all checks (including the null checks) but now I see you were probably only talking about "loadingViewController.shown" check. I have removed it.

File: Kuroba/app/src/main/java/com/github/adamantcheese/chan/core/manager/UpdateManager.java (hunk 18 above)
Comment (K1rakishou) [reply Kuroba/app/src/main/java/com/github/adamantcheese/chan/core/manager/UpdateManager.java]: Alright, periods in file names should work fine now. But not in directory names! I don't think we should allow periods in directory names.

File: Kuroba/app/src/main/java/com/github/adamantcheese/chan/core/cache/downloader/PartialContentSupportChecker.kt (hunk 40 above)
Comment (K1rakishou) [reply Kuroba/app/src/main/java/com/github/adamantcheese/chan/core/cache/downloader/PartialContentSupportChecker.kt]: Damn, this one will take more time than I expected.

File: Kuroba/app/src/main/java/com/github/adamantcheese/chan/core/presenter/ImageViewerPresenter.java (hunk 25 above)
Comment (Adamantcheese) [reply Kuroba/app/src/main/java/com/github/adamantcheese/chan/core/presenter/ImageViewerPresenter.java:111]: Code reuse? And that still doesn't answer my question; "it's not a power of two" doesn't explain WHY it needs to be a power of two. If I'm downloading a 24KB file with a minimum chunk size of 8KB, then 1, 2, 3, 4, 6, 8, etc. chunks are all divisible without remainder.

Comment (K1rakishou) [reply Kuroba/app/src/main/java/com/github/adamantcheese/chan/core/presenter/ImageViewerPresenter.java:111]: There is no specific reason for why I didn't include 3 into the options other than it not being a power of two. I can include it if you want.

>If I'm downloading a 24KB file with a minimum chunk size of 8KB, then 1, 2, 3, 4, 6, 8, etc. chunks are all divisible without remainder.

It really doesn't matter whether it's 2 or 3 or 4 other than a little bit of speed up with a higher number (which gets to the point of no difference after the 4). Even if I use a prime number for the chunks count it still will be fine, because if the total amount of bytes is not divisble by the chunk count without the remainder then the remainer will be added up to the last chunk.

>Code reuse?

There is not really that much new code because of it other than the new enum.

Comment (K1rakishou) [reply Kuroba/app/src/main/java/com/github/adamantcheese/chan/core/presenter/ImageViewerPresenter.java:111]: Another reason in favor of using a predifined list of options instead of allowing the user to enter a number by himself is that the user cannot know the possible range of the value he needs to enter so he will probably try entering something like 100, then he will see an error message, then 50, error message again and so on until he enters a number between 1-4. And then the user may ask a question: "Why in the fuck was it not implemented with a predifined list of options if there are only 4 possible options?". And if we provide a hint that the number must be 1-4 then it will make this thing even more ridiculous.

So, basically, what I'm trying to say is that there are way too few options to use IntegerSettingView.

File: Kuroba/app/src/main/java/com/github/adamantcheese/chan/ui/widget/CancellableToast.kt (hunk 33 above)
Comment (K1rakishou) [reply Kuroba/app/src/main/java/com/github/adamantcheese/chan/ui/widget/CancellableToast.kt:1]: But maybe I should also add a cancel button to the LoadingControllerView?

File: Kuroba/app/src/main/java/com/github/adamantcheese/chan/core/cache/downloader/PartialContentSupportChecker.kt (hunk 40 above)
Comment (K1rakishou) [reply Kuroba/app/src/main/java/com/github/adamantcheese/chan/core/cache/downloader/PartialContentSupportChecker.kt]: Done.

File: Kuroba/app/src/main/java/com/github/adamantcheese/chan/core/cache/CacheHandler.kt (hunk 23 above)
Comment (K1rakishou) [reply Kuroba/app/src/main/java/com/github/adamantcheese/chan/core/cache/CacheHandler.kt:675]: Well, yes, this will probably work but still I don't really want to change this code because I've been testing it for weeks and if I change it now I will have to test it again. There are even unit-tests and shit. 

Are there any other reasons to change it other than it been kinda complex (it's not really  that complex, it's just two variables in a file that I read/update and if I can't access the file, or read the data, for some reason, I just delete both so the file can be redownloaded)? Because this reason is not really motivating enough to change it.

File: Kuroba/app/src/main/java/com/github/adamantcheese/chan/core/di/NetModule.java (hunk 20 above)
Comment (K1rakishou) [reply Kuroba/app/src/main/java/com/github/adamantcheese/chan/core/di/NetModule.java:55]: Actually, do we really want to add it there. Because from what I can see in this commit 

>"Use a fileprovider to open videos in external apps"

I assume that the directory was added to that file so that an external video player is able to play video files in that directory. And since files in "file_chunks_cache" will never be played in a video player I guess I don't need to add it there?

Comment (K1rakishou) [reply Kuroba/app/src/main/java/com/github/adamantcheese/chan/core/di/NetModule.java:55]: And Android already knows what to do with those files since they are in a cache directory. Android will just delete them when it's necessary.

File: Kuroba/app/src/main/java/com/github/adamantcheese/chan/ui/controller/AlbumDownloadController.java (hunk 36 above)
Comment (Adamantcheese) [reply Kuroba/app/src/main/java/com/github/adamantcheese/chan/ui/controller/AlbumDownloadController.java]: You've said you've removed it, but the current status of your branch says otherwise. Did you forget to push something?
