### PR TITLE
(#381) Implement "retry on IO error" file downloading strategy

### LINKED ISSUE #381: [IMPROVEMENT] Small fixes for FileCacheDownloader
Right now if some exception occurrs while reading data from the socket (`Sink`) it will fail the file downloading right away which is bad when the network is flaky. What should be done in this case is the downloading should be restarted whenever an `IOException` was thrown for couple of times (lets say 3 times and if it still fails with `IOException` then fail the whole downloading).

~~Also I have noticed that we may not close some closeable resources when exception occurrs in `pipeBody()` method:~~

~~https://github.com/Adamantcheese/Kuroba/blob/multi-feature/Kuroba/app/src/main/java/com/github/adamantcheese/chan/core/cache/FileCacheDownloader.java#L255~~

~~If `source.read()` throws an exception then we won't close nor source nor sink nor the body of the response which will cause a memory leak and probably some other leak as well.~~

I'm also thinking about converting this whole class into Kotlin and using Kotlin coroutines there.

### PR DESCRIPTION
**Pull request by K1rakishou**
- Now when downloading a file and an IO exception is thrown we will try downloading the same file again (up to 3 times) and only when there are no more attempts left we will cancel the downloading.
- Convert FileCacheDownloader into Kotlin
- Add lots of main/background thread checks to make sure everything is consistent (when downloading files).
- Show the cause of the error when we couldn't download files to the user (so they can report it).
- Remove kotlin-kapt for now. We don't use it right now  and it was causing compilation errors sometimes. Will bring it back once we actually need it in the project.
- Also, explicitly add timeouts for ProxiedOkHttpClient (it's not obvious whether they are set or not)

Closes #381

### CODE REVIEW

**Comment by Adamantcheese** [comment]
You've added... like way too many main thread checks. There's a number of places where it's guaranteed to be executing on the main thread without needing to check it. I get that safety is good to prevent crashes as much as possible, but I'm getting the feeling that one of these is going to randomly crash the application instead of just warning in the log, which will be really annoying. Same thing goes for background thread checks.

**Comment by K1rakishou** [comment]
We have dev builds now so it will be pretty easy to check them all (I have manually checked most of them). I'm pretty much using only the dev build now so I will probably notice it if crashes. And I think fail-fast strategy is better than fail-safe. And with the checks we have a guarantee that those methods are being executed on the right threads (So we need even more of them for the whole app). And if you change them to warnings then nobody will care.

**Comment by Adamantcheese** [comment]
For a user-facing application, fail-safe is better than fail-fast. If you want to keep the checks in, I need you to add in a debug build check to your `ensureMainThread` and `ensureBackgroundThread` functions so they aren't executed on release builds. Only the developers should care if something is being executed on the right thread. The user has no need to know or care about that and will be more confused if crashes randomly happen from doing normal operations.

**Comment by K1rakishou** [comment]
>I need you to add in a debug build check to your ensureMainThread and ensureBackgroundThread functions so they aren't executed on release builds.

That's actually a pretty good idea. I will do it. In case of the release build they will be just spewing warnings to the log.

**Comment by K1rakishou** [comment]
This PR is actually ready to be merged.

File: Kuroba/app/src/main/java/com/github/adamantcheese/chan/core/cache/FileCacheDownloader.kt [hunk 1]
```diff
@@ -0,0 +1,385 @@
...
+     * Cancel this download.
+     */
+    @MainThread
+    fun cancel() {
+        BackgroundUtils.ensureMainThread()
+
+        if (cancel.compareAndSet(false, true)) {
+            // Did not start running yet, mark finished here.
+            if (!running.get() && callback != null) {
+                Thread.currentThread().interrupt();
```
Comment (K1rakishou) [inline Kuroba/app/src/main/java/com/github/adamantcheese/chan/core/cache/FileCacheDownloader.kt]: Uhhh, this may actually not be good because this will interrupt the main thread.

Comment (K1rakishou) [reply Kuroba/app/src/main/java/com/github/adamantcheese/chan/core/cache/FileCacheDownloader.kt]: Gonna fix this today, do not merge this one yet.

**Comment by K1rakishou** [comment]
Alright, it's ready to be merged.
