### PR TITLE
(#600) Notification system for settings (for crash logs and apk updates)

### LINKED ISSUE #600: [IMPROVEMENT] Make automatic crash reporting not as sneaky as it is right now
What I'm thinking of doing is not just adding a dialog that will be thrown in your face every time you open the app after it crashed (this shit will make anyone angry and they will just disable it completely) but implementing a notification system, but not with android notifications, but rather how unread posts/yous notification works (the little circle with numbers on top of the three line menu). So, basically, if crash logs are enabled and you have unsent crash logs another circle will appear (with exclamation mark or something similar) notifying that there are new crash logs to be uploaded.

### PR DESCRIPTION
**Pull request by K1rakishou**
Closes #600

~~Not ready yet.~~

So, basically, instead of spamming AlertDialogs on every important update (like new apk update or new crash log that awaits to be either uploaded or not) there is now a more user-friendly system which does not nag the user with any windows whatsoever. Instead, a small alert icon is being shown in specific setting option (and in the drawer too) so the user sees it every time he opens the drawer or the settings. Once the conditions for this icon are all satisfied it disappears (like all crash logs are either uploaded or deleted). If there are multiple notifications (say apk update and couple crash logs) then a notification with highest priority is shown in the drawer (once it's cleared the other one replaces it, etc).

It's pretty easy to add new notifications, too.

Oh yeah, you can now also review crash logs and decide which you upload and which not (you can even delete them all). No crash logs are now being uploaded automatically.

### CODE REVIEW

**Comment by K1rakishou** [comment]
Alright, now it's ready.

**Comment by K1rakishou** [comment]
I had to change a couple of things in UpdateManager so you better review it more carefully.

File: Kuroba/app/src/main/java/com/github/adamantcheese/chan/ui/controller/settings/MainSettingsController.java [hunk 1]
```diff
@@ -204,4 +251,73 @@ private void setupAboutGroup() {
...
+
+        if (crashLogsCount > 0) {
+            suggestSendingCrashLogs(crashLogsCount);
+            return;
+        }
+
+        openReportProblemController();
+    }
+
+    private void suggestSendingCrashLogs(int crashLogsCount) {
```
Comment (K1rakishou) [inline Kuroba/app/src/main/java/com/github/adamantcheese/chan/ui/controller/settings/MainSettingsController.java]: Probably should be called "SuggestReviewCrashLogs"

File: Kuroba/app/src/main/java/com/github/adamantcheese/chan/ui/layout/crashlogs/CrashLog.kt [hunk 2]
```diff
@@ -0,0 +1,24 @@
+package com.github.adamantcheese.chan.ui.layout.crashlogs
+
+import java.io.File
+
+data class CrashLog(val file: File, val fileName: String, var send: Boolean) {
```
Comment (K1rakishou) [inline Kuroba/app/src/main/java/com/github/adamantcheese/chan/ui/layout/crashlogs/CrashLog.kt]: "send" should actually be called "selected" or something

File: Kuroba/app/src/main/java/com/github/adamantcheese/chan/core/manager/SettingsNotificationManager.kt [hunk 3]
```diff
@@ -0,0 +1,94 @@
+package com.github.adamantcheese.chan.core.manager
+
+import com.github.adamantcheese.chan.ui.settings.SettingNotificationType
+import com.github.adamantcheese.chan.utils.Logger
+import io.reactivex.Flowable
+import io.reactivex.android.schedulers.AndroidSchedulers
+import io.reactivex.processors.BehaviorProcessor
+
+class SettingsNotificationManager {
+    private val notifications: MutableSet<SettingNotificationType> = mutableSetOf()
```
Comment (K1rakishou) [inline Kuroba/app/src/main/java/com/github/adamantcheese/chan/core/manager/SettingsNotificationManager.kt:12]: Probably should add "@GuardedBy("this")"

File: Kuroba/app/src/main/java/com/github/adamantcheese/chan/core/manager/SettingsNotificationManager.kt [hunk 4]
```diff
@@ -0,0 +1,94 @@
...
+    }
+
+    /**
+     * Use this to observe current notification state. Duplicates checks and everything else is done
+     * internally so you don't have to worry that you will get the same state twice. All updates
+     * come on main thread so there is no need to worry about that as well.
+     * */
+    fun listenForNotificationUpdates(): Flowable<Unit> = activeNotificationsSubject
+            .onBackpressureBuffer()
+            .observeOn(AndroidSchedulers.mainThread())
```
Comment (K1rakishou) [inline Kuroba/app/src/main/java/com/github/adamantcheese/chan/core/manager/SettingsNotificationManager.kt:91]: Use `hide()` here.

File: Kuroba/app/src/main/java/com/github/adamantcheese/chan/core/manager/UpdateManager.java [hunk 5]
```diff
@@ -168,7 +179,7 @@ private void runUpdateApi(final boolean manual) {
         if (!BuildConfig.DEV_BUILD) {
             //region Release build
             volleyRequestQueue.add(new UpdateApiRequest(response -> {
-                if (!processUpdateApiResponse(response) && manual && BackgroundUtils.isInForeground()) {
+                if (!processUpdateApiResponse(response, manual && BackgroundUtils.isInForeground()) && manual) {
```
Comment (K1rakishou) [inline Kuroba/app/src/main/java/com/github/adamantcheese/chan/core/manager/UpdateManager.java]: Uhh, something broke here after merge? This doesn't seem correct.

File: Kuroba/app/src/main/java/com/github/adamantcheese/chan/core/manager/UpdateManager.java [hunk 6]
```diff
@@ -227,25 +240,49 @@ private void runUpdateApi(final boolean manual) {
...
+            notifyNewApkUpdate();
             return true;
         }
+
+        cancelApkUpdateNotification();
         return false;
     }
 
+    private void notifyNewApkUpdate() {
+        ChanSettings.hasNewApkUpdate.set(true);
```
Comment (K1rakishou) [inline Kuroba/app/src/main/java/com/github/adamantcheese/chan/core/manager/UpdateManager.java]: This is not a setting. This is a persistable app state. I think I should extract it into a separate class that uses it's own shared preferences file.

File: Kuroba/app/src/main/java/com/github/adamantcheese/chan/ui/controller/DrawerController.java [hunk 7]
```diff
@@ -62,14 +68,20 @@
...
         implements DrawerAdapter.Callback, View.OnClickListener {
+    private static final String TAG = "DrawerController";
+
     protected FrameLayout container;
     protected DrawerLayout drawerLayout;
     protected LinearLayout drawer;
     protected RecyclerView recyclerView;
     protected DrawerAdapter drawerAdapter;
+    @Nullable
+    private CompositeDisposable compositeDisposable = null;
```
Comment (K1rakishou) [inline Kuroba/app/src/main/java/com/github/adamantcheese/chan/ui/controller/DrawerController.java]: Probably shouldn't make it nullable. Just create it once and then use clear() instead of dispose()

File: Kuroba/app/src/main/java/com/github/adamantcheese/chan/ui/controller/settings/SettingsController.java [hunk 8]
```diff
@@ -39,30 +44,40 @@
...
+
     protected LinearLayout content;
     protected List<SettingsGroup> groups = new ArrayList<>();
-
     protected List<SettingView> requiresUiRefresh = new ArrayList<>();
-
     // Very user unfriendly.
     protected List<SettingView> requiresRestart = new ArrayList<>();
-
+    protected CompositeDisposable compositeDisposable;
```
Comment (K1rakishou) [inline Kuroba/app/src/main/java/com/github/adamantcheese/chan/ui/controller/settings/SettingsController.java]: Don't make it nullable. Create it once and then use clear() instead of dispose()

File: Kuroba/app/src/main/java/com/github/adamantcheese/chan/core/manager/UpdateManager.java (hunk 6 above)
Comment (Adamantcheese) [reply Kuroba/app/src/main/java/com/github/adamantcheese/chan/core/manager/UpdateManager.java]: You probably won't need a setting at all since the update API is run on every startup.

Comment (K1rakishou) [reply Kuroba/app/src/main/java/com/github/adamantcheese/chan/core/manager/UpdateManager.java]: But it only checks for the new apk only once in 24h, or is it not?

**Comment by K1rakishou** [comment]
~~I should also only upload crashes that are not older than, let's say, 3 days (and delete older crashes) to avoid endless spam. Also should check and handle http codes 429 (when client attempted to send way too many crash logs) and 500.~~

Already done in another PR and already merged.

File: Kuroba/app/src/main/java/com/github/adamantcheese/chan/core/manager/UpdateManager.java (hunk 6 above)
Comment (Adamantcheese) [reply Kuroba/app/src/main/java/com/github/adamantcheese/chan/core/manager/UpdateManager.java]: It checks for a new APK only when the app is started cold, with a minimum delay of 24h for dev and 5 days for stable. There's no scheduled task to check for an update, just like how it was in Clover.

Comment (K1rakishou) [reply Kuroba/app/src/main/java/com/github/adamantcheese/chan/core/manager/UpdateManager.java]: Well that's why I needed "hasNewApkUpdate" flag. Because if we start the app during the 24h or 5d window when we do not check for the updates, and there were actually an update the last time we checked it, the notification won't show up.

Comment (Adamantcheese) [reply Kuroba/app/src/main/java/com/github/adamantcheese/chan/core/manager/UpdateManager.java]: Ah okay, I understand. You're setting it in case someone runs the updater manually, but defers installation to a later point.

Comment (Adamantcheese) [reply Kuroba/app/src/main/java/com/github/adamantcheese/chan/core/manager/UpdateManager.java]: It's still fine to keep it in ChanSettings anyways, there's a bunch of things in there that aren't strictly settings.

Comment (K1rakishou) [reply Kuroba/app/src/main/java/com/github/adamantcheese/chan/core/manager/UpdateManager.java]: Well those will have to be moved too. But we can do that later. Or I could move them.

Comment (Adamantcheese) [reply Kuroba/app/src/main/java/com/github/adamantcheese/chan/core/manager/UpdateManager.java]: Please just keep it to one thing per PR if possible, these super huge PRs with all sorts of barely related stuff in them makes it difficult to review.

Comment (K1rakishou) [reply Kuroba/app/src/main/java/com/github/adamantcheese/chan/core/manager/UpdateManager.java]: Alright then I will just move this one setting to a new class.

Comment (K1rakishou) [reply Kuroba/app/src/main/java/com/github/adamantcheese/chan/core/manager/UpdateManager.java]: Done.

File: Kuroba/app/src/main/java/com/github/adamantcheese/chan/core/manager/ReportManager.kt [hunk 9]
```diff
@@ -169,37 +179,97 @@ class ReportManager(
...
+
+        val potentialCrashLogs = crashLogsDirPath.listFiles()
+        if (potentialCrashLogs.isNullOrEmpty()) {
+            Logger.d(TAG, "No new crash logs")
+            settingsNotificationManager.cancel(SettingNotificationType.CrashLogs)
+            return
+        }
+
+        potentialCrashLogs.asSequence()
+                .filter { file -> file.name.startsWith(CRASH_LOG_FILE_NAME_PREFIX) }
```
Comment (K1rakishou) [inline Kuroba/app/src/main/java/com/github/adamantcheese/chan/core/manager/ReportManager.kt]: Probably should remove this `filter` operator because only crash logs are supposed to be stored in that directory anyway so everything should be deleted.

File: Kuroba/app/src/main/java/com/github/adamantcheese/chan/core/manager/SettingsNotificationManager.kt [hunk 10]
```diff
@@ -0,0 +1,97 @@
...
+import io.reactivex.Flowable
+import io.reactivex.android.schedulers.AndroidSchedulers
+import io.reactivex.processors.BehaviorProcessor
+
+class SettingsNotificationManager {
+    @GuardedBy("this")
+    private val notifications: MutableSet<SettingNotificationType> = mutableSetOf()
+
+    /**
+     * A reactive stream that is being used to notify observer about [notifications] changes
```
Comment (K1rakishou) [inline Kuroba/app/src/main/java/com/github/adamantcheese/chan/core/manager/SettingsNotificationManager.kt]: observers

File: Kuroba/app/src/main/java/com/github/adamantcheese/chan/core/manager/SettingsNotificationManager.kt [hunk 11]
```diff
@@ -0,0 +1,97 @@
...
+        }
+    }
+
+    @Synchronized
+    fun getNotificationByPriority(): SettingNotificationType? {
+        if (contains(SettingNotificationType.ApkUpdate)) {
+            return SettingNotificationType.ApkUpdate
+        }
+
+        if (contains(SettingNotificationType.CrashLogs)) {
```
Comment (K1rakishou) [inline Kuroba/app/src/main/java/com/github/adamantcheese/chan/core/manager/SettingsNotificationManager.kt]: Maybe I should rename it to CrashLog?

File: Kuroba/app/src/main/java/com/github/adamantcheese/chan/core/settings/ChanState.kt [hunk 12]
```diff
@@ -0,0 +1,24 @@
+package com.github.adamantcheese.chan.core.settings
+
+import com.github.adamantcheese.chan.utils.AndroidUtils
+import com.github.adamantcheese.chan.utils.Logger
+
+
+object ChanState {
```
Comment (K1rakishou) [inline Kuroba/app/src/main/java/com/github/adamantcheese/chan/core/settings/ChanState.kt]: Actually this class is still unmockable. I need to create an interface with all the settings methods and inherit this singleton from the interface. And with that I will be able to create mocks of the interface.

File: Kuroba/app/src/main/java/com/github/adamantcheese/chan/core/settings/ChanState.kt [hunk 13]
```diff
@@ -0,0 +1,24 @@
...
+            hasNewApkUpdate = BooleanSetting(p, "has_new_apk_update", false)
+        } catch (error: Throwable) {
+            Logger.e(TAG, "Error while initializing the state", error)
+            throw error
+        }
+    }
+
+    // Why? So it can be mocked in tests.
+    @JvmStatic
+    open fun hasNewApkUpdate() = hasNewApkUpdate
```
Comment (K1rakishou) [inline Kuroba/app/src/main/java/com/github/adamantcheese/chan/core/settings/ChanState.kt]: And I guess I should provide two methods: get and set so it doesn't need to return String/Boolean/whatever setting which I will have to mock too.
