### PR TITLE
(#484) Fix parsing exception when parsing dead crossboard link

### LINKED ISSUE #484: [bug] Exception in DefaultPostParser when parsing a dead crossboard link
Posts containing dead cross-board links seem to show up as blank posts.
JointPics_20191230_194148

### PR DESCRIPTION
**Pull request by K1rakishou**
Closes #484

Should be merged after https://github.com/Adamantcheese/Kuroba/issues/480 because it depends on it.

### CODE REVIEW

File: Kuroba/app/src/main/java/com/github/adamantcheese/chan/core/site/parser/CommentParser.java [hunk 1]
```diff
@@ -243,9 +246,30 @@ public CharSequence handleDead(
...
-        int postNo = Integer.parseInt(Parser.unescapeEntities(deadlink.text(), true).substring(2));
+        // Or like this &gt;&gt;&gt;/int/116000000 in case of a dead crossboard link
+
+        String deadlinkText = deadlink.text();
+        int postNo = -1;
+
+        try {
+            // Handle the crossboard dead link first, because otherwise the condition will be always
+            // true. The order of conditions matters!
+            if (deadlinkText.startsWith(">>>")) {
```
Comment (Adamantcheese) [inline Kuroba/app/src/main/java/com/github/adamantcheese/chan/core/site/parser/CommentParser.java:257]: This won't work at all. There's a reason why I unescape entities first before doing anything else, because `&gt;&gt;&gt;` is not equal to `>>>` at all.

**Review by Adamantcheese — CHANGES_REQUESTED** [review]

File: Kuroba/app/src/main/java/com/github/adamantcheese/chan/core/site/parser/CommentParser.java (hunk 1 above)
Comment (K1rakishou) [reply Kuroba/app/src/main/java/com/github/adamantcheese/chan/core/site/parser/CommentParser.java:257]: Either I do not understand something or it does unescape them automatically when calling text(). The same goes for ">>>"

Comment (K1rakishou) [reply Kuroba/app/src/main/java/com/github/adamantcheese/chan/core/site/parser/CommentParser.java:257]: I guess Parser.unescapeEntities() is not needed at all? Because it doesn't do anything since it's already unescaped.

Comment (Adamantcheese) [reply Kuroba/app/src/main/java/com/github/adamantcheese/chan/core/site/parser/CommentParser.java:257]: I should probably read the comment on the function next time, because it says that it's unencoded.

**Comment by Adamantcheese** [comment]
On second look, this is entirely wrong, as a crossboard link in the OP likely won't be linking to a thread. I'll do this one myself.
