### PR TITLE
(#298) Pin watcher fix

### LINKED ISSUE #298: [BUG] PinWatcher service starts when all pins get archived or deleted
Basically, because of an error in this check https://github.com/Adamantcheese/Kuroba/blob/multi-feature/Kuroba/app/src/main/java/com/github/adamantcheese/chan/core/manager/WatchManager.java#L699 when we have no local thread for a pin will be set to false which will then set allPinsHaveCompletedDownloading  to false and because of that the service will be started.

### PR DESCRIPTION
**Pull request by K1rakishou**
Closes #298

### CODE REVIEW

File: Kuroba/app/src/main/java/com/github/adamantcheese/chan/core/site/loader/ChanThreadLoader.java [hunk 1]
```diff
@@ -603,27 +603,29 @@ public void onErrorResponse(VolleyError error) {
...
-            }
+        if (loadable == null) {
+            Logger.d(TAG, "Could not get current loadable, it's null");
+            return null;
+        }
 
-            if (!PinType.hasDownloadFlag(pin.pinType)) {
-                return null;
-            }
+        Pin pin = Chan.injector().instance(WatchManager.class).findPinByLoadableId(loadable.id);
```
Comment (K1rakishou) [inline Kuroba/app/src/main/java/com/github/adamantcheese/chan/core/site/loader/ChanThreadLoader.java:611]: Uhhh, this PR should be merged only after #305 is merged, Also this line should be changed to watchManager.findPinByLoadableId(loadable.id);

Comment (Adamantcheese) [reply Kuroba/app/src/main/java/com/github/adamantcheese/chan/core/site/loader/ChanThreadLoader.java:611]: Alright.
